% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{book}
\title{GEOG0125: Advanced Topics in Social Geographic Data Science}
\author{}
\date{\vspace{-2.5em}}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={GEOG0125: Advanced Topics in Social Geographic Data Science},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{plainnat}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{welcome}{%
\chapter*{Welcome}\label{welcome}}
\addcontentsline{toc}{chapter}{Welcome}

\begin{center}\includegraphics[width=1\linewidth]{images/general/UCL_MSC_SDGS_banner} \end{center}

Welcome to \textbf{GEOG0125: Advanced Topics in Social Geographic Data Science}, one of the optional modules for this MSc programme (\href{https://www.geog.ucl.ac.uk/study/graduate-taught/msc-social-and-geographic-data-science}{\textbf{Social and Geographic Data Science}}). This module has been designed as an advanced topics module to learn data science concepts and methods, and to apply them in the domains of social science and geography. The module will introduce concepts such as statistical inference and machine learning methodologies.

In the first three weeks, you will be introduced to \textbf{descriptive} and \textbf{inferential statistical techniques} in RStudio. Afterwards, in week 4, 5 and 6, we will cover a variety of unique machine learning techniques which includes \textbf{Deep Learning}, \textbf{Convolutional Neural Networks} and \textbf{GeoAI} in Python. In week 7, 8, 9 and 10, we will introduced to \textbf{Bayesian statistics using INLA} to get perform geospatial analysis of point, areal and raster data. This will cover \textbf{Spatial Temporal Modelling} as well as \textbf{SPDE-INLA}. Lastly, you will gain the practical skills for building dashboards for \textbf{Web \& Geo-visualisation using R-Shiny}.

\hypertarget{moodle}{%
\section*{Moodle}\label{moodle}}
\addcontentsline{toc}{section}{Moodle}

All practical materials including reading lists and downloadable data sets will be hosted on this webpage. The lecture materials, including live stream recordings will be on \href{https://moodle.ucl.ac.uk/}{\textbf{Moodle}}.

\textbf{Moodle} is the central point of your learning experience for \textbf{GEOG0125} and contains everything you need to know about the schedule for weekly topics and assessment. Do check Moodle on a regular basis for any important updates.

\hypertarget{structure}{%
\section*{Structure}\label{structure}}
\addcontentsline{toc}{section}{Structure}

All lectures and computer practicals are in-person. The computer lessons are delivered a day before the lectures. All computer lab seminars will be delivered on Thursday from 09:00am to 11:00am at the \href{https://www.ucl.ac.uk/maps/cruciform-building}{\textbf{Cruciform Building (Room B1.15A)}}. All Lectures are held on Friday from 11:00am to 12:00pm at the \href{https://www.ucl.ac.uk/maps/north-west-wing-building}{\textbf{North West Wing (Room 305)}}.

\hypertarget{office-hours-for-geog0125}{%
\section*{Office hours for GEOG0125}\label{office-hours-for-geog0125}}
\addcontentsline{toc}{section}{Office hours for GEOG0125}

\begin{itemize}
\item
  Office hours with Dr Anwar Musah (Thursdays between 12h00 and 13h00)
\item
  Office hours with Lan Li (Thursdays between 12h00 and 14h00)
\end{itemize}

Feel free to drop-by in-person at our offices for additional support. Our contact information and office details are:

\textbf{Dr Anwar Musah}
UCL Department of Geography
Room 115, North West Wing Building, WC1E 6BT
Email: \href{a.musah@ucl.ac.uk}{\textbf{a.musah@ucl.ac.uk}}

\textbf{Lan Li}
UCL Institute for Risk \& Disaster Reduction
Room 32a, Centre for Digital Public Health \& Emergencies
\href{http://www.ucl.ac.uk/maps/south-wing}{\textbf{2nd Floor, South Wing Building, WC1E 6BT}}
Email: \href{**lan.li.19@ucl.ac.uk**}{\textbf{lan.li.19@ucl.ac.uk}}

\hypertarget{descriptive-statistics}{%
\chapter{Descriptive Statistics}\label{descriptive-statistics}}

\textbf{Theme: Fatal encounters with Police (USA)}

\begin{center}\includegraphics[width=1\linewidth]{images/general/Nighttime_police_image} \end{center}

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

This week is a simple exercise. We take a look at how descriptive analyses are applied to data with regards to fatal encounters with the police in the United States of America. The use of deadly force or excessive violence by those affiliated with the law enforcement against suspects and civilians is a problematic matter in America's society. It is a social problem that predominately affects people who are already disadvantaged in life, and are in deprived areas where the social-dynamic and relationship between the police and citizen are fractured.

We can going to use an excerpt data from a brilliant source, \href{https://fatalencounters.org}{\textbf{Fatal Encounters Database}}, which is an open source database containing details about deaths through police interaction in the United States. These records have been documented since January 1st, 2000. We will carry out some simple descriptive analysis to examine the burden of such fatal encounters in the USA from 2013 and 2020, inclusively. At the end of this session, you should be able to perform the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Descriptive analysis using frequency distribution tables in RStudio
\item
  Descriptive analysis of continuous variables with central tendency \& dispersion measures
\item
  How to create customizable descriptive summary tables in RStudio
\item
  Graphical visualisations using various plots
\end{enumerate}

\hypertarget{downloadable-dataset-for-this-exercise}{%
\subsection{Downloadable dataset for this exercise}\label{downloadable-dataset-for-this-exercise}}

Make sure to download the data set for Week 1 from \href{https://github.com/UCLPG-MSC-SGDS/GEOG0125/raw/main/Dataset.zip}{\textbf{HERE}}. The data file is named \texttt{WK01\ -\ Fatal\ Encounters\ with\ Police.csv} Here is the data descriptor:

\begin{longtable}[]{@{}ll@{}}
\toprule
\textbf{Variable Name} & \textbf{Description} \\
\midrule
\endhead
UniqueID & Unique identification number \\
Name & Name of victim \\
Age & Age of victim (in years) \\
Gender & ``Male'' or ``Female'' \\
City & City location of fatal encounter \\
State & State of fatal encounter \\
ZipCode & Zip code \\
County & County of fatal encounter \\
Latitude & Latitude (in decimal degrees) \\
Longitude & Longitude (in decimal degrees) \\
LethalForceType & Type of lethal force used by Police \\
FleeingStatus & Was the suspect or civilian trying to flee? \\
ArmedStatus & Was the suspect or civilian carrying a weapon? \\
AggressionSign & Did the victim aggressive? \\
Ethnicity & Ethnicity \\
DeathYear & Year of death due to police encounter \\
\bottomrule
\end{longtable}

\hypertarget{reading-list}{%
\subsection{Reading list}\label{reading-list}}

Please find reading list for this week:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Recommended Book: Dalgaard, P. (2008). \textbf{Introductory Statistics with R (Second Edition)}. Chapter 4: Descriptive statistics and graphics. Pages 67 to 93 \href{https://link.springer.com/book/10.1007/978-0-387-79054-1}{(\textbf{Download Ebook here})}
\item
  Recommended Book: Zuur, A.F., Ieno, E.N. \& Meesters, E.H.W.G., (2009). \textbf{A Beginner's Guide to R. Chapter 7: Graphing Tools}. Pages 127 to 167 \href{https://link.springer.com/book/10.1007/978-0-387-93837-0}{(\textbf{Download Ebook here})}
\end{enumerate}

\hypertarget{frequency-distribution}{%
\section{Frequency distribution}\label{frequency-distribution}}

Let us begin by importing our week's 1 data set into RStudio and calling the data frame \texttt{FatalEncounters}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Set your own directory using setwd() function}
\CommentTok{\# Load data into RStudio using read.csv(). The spreadsheet is stored in the object called \textquotesingle{}FatalEncounters\textquotesingle{}}
\NormalTok{FatalEncounters }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"WK01 {-} Fatal Encounters with Police.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The simplest operation of a descriptive analysis is a \textbf{frequency distribution}. The frequency table allows the user to display the frequency of various outcomes in a sample. There are \texttt{9,119} deaths in this data set - each row in this data set represents a death of a civilian or suspect caused police using lethal force.

One can easily generate a summary frequency tables for the number of fatal encounters based on a nominal or ordinal categorical characteristic using the \texttt{table()} of the fly.

For instance, suppose if you wanted to tabulate the frequency of fatal encounters based on the type of lethal force used by a law enforcer. You can type the following code:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# tabulating number of fatal encounters using a nominal variable}
\FunctionTok{table}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{LethalForceType)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##          Gunshot Physical Assault          Vehicle 
##             6609              602             1908
\end{verbatim}

This shows the absolute number of fatal encounters with the police. You can report the prevalence of death based on the type of deadly force simply by using the \texttt{prop.table()}:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# To get the prevalence (or proportions) of fatal encounters based on a nominal variable}
\CommentTok{\# {-}{-}{-} tabulate result and pass it into the prop.table() function}
\NormalTok{result }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{LethalForceType)}
\FunctionTok{prop.table}\NormalTok{(result)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##          Gunshot Physical Assault          Vehicle 
##       0.72475052       0.06601601       0.20923347
\end{verbatim}

We have the absolute numbers and the proportions separated - we can bring these results together by using the \texttt{transform()} which is much useful:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# To get the prevalence (or proportions) of fatal encounters based on a nominal variable}
\CommentTok{\# {-}{-}{-} tabulate result and pass it into the transform() function. The Proportion is an argument with}
\CommentTok{\# {-}{-}{-} prop.table(Freq) always}

\NormalTok{result }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{LethalForceType)}
\FunctionTok{transform}\NormalTok{(result, }\AttributeTok{Proportions =} \FunctionTok{prop.table}\NormalTok{(Freq))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               Var1 Freq Proportions
## 1          Gunshot 6609  0.72475052
## 2 Physical Assault  602  0.06601601
## 3          Vehicle 1908  0.20923347
\end{verbatim}

\textbf{Interpretation}: In the United States, the use of either a gun, a vehicle or physical force by police resulted in the deaths of \texttt{6,609\ (73\%)}, \texttt{1,908\ (21\%)} or \texttt{602\ (6\%)} suspects (or civilians) respectively.

\hypertarget{computing-frequencies-cumulative-frequency-and-proportions}{%
\subsection{Computing frequencies, cumulative frequency and proportions}\label{computing-frequencies-cumulative-frequency-and-proportions}}

Suppose we want to compute the frequency distribution of these fatal encounters based on some continuous variable such as age (in years). We can perform this univariable analysis to summarise the number of deaths with the age distribution with fixed ranges to compute frequency, cumulative frequency and proportions.

To do this, we first create bins (or groups) for the age ranges by gauging the the minimum and maximum age value with \texttt{min()} and \texttt{max()} function, and create the bins with the \texttt{cut()} function using some interval.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{min}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{Age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{max}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{Age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 107
\end{verbatim}

The victim with the lowest age was 10 years, and the oldest was 101 years. Now, we create a new \texttt{Bins} column from 5 (based from lowest value) to 110 (i.e., based on the highest which is 101) at intervals of 10 years to look something like \texttt{10-20}, \texttt{21-30}, \texttt{31-40}, \texttt{41-50}, \texttt{51-60},\texttt{61-70}, \texttt{71-80}, \texttt{81-90}, \texttt{91-100} and \texttt{101-110} by cutting the \texttt{Age} variable using the \texttt{cut()} function. This will help us to create the desired frequency distribution table in RStudio.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# starting from 5 to ensure lowest number 10 is counted in the breaks and vice versa for highest}
\NormalTok{FatalEncounters}\SpecialCharTok{$}\NormalTok{Bins }\OtherTok{\textless{}{-}} \FunctionTok{cut}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{Age, }\AttributeTok{breaks=}\FunctionTok{c}\NormalTok{(}\DecValTok{5}\NormalTok{, }\DecValTok{20}\NormalTok{, }\DecValTok{30}\NormalTok{, }\DecValTok{40}\NormalTok{, }\DecValTok{50}\NormalTok{, }\DecValTok{60}\NormalTok{, }\DecValTok{70}\NormalTok{, }\DecValTok{80}\NormalTok{, }\DecValTok{90}\NormalTok{, }\DecValTok{100}\NormalTok{, }\DecValTok{110}\NormalTok{), }\AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"\textless{}20"}\NormalTok{,}\StringTok{"21{-}30"}\NormalTok{,}\StringTok{"31{-}40"}\NormalTok{,}\StringTok{"41{-}50"}\NormalTok{,}\StringTok{"51{-}60"}\NormalTok{,}\StringTok{"61{-}70"}\NormalTok{,}\StringTok{"71{-}80"}\NormalTok{,}\StringTok{"81{-}90"}\NormalTok{,}\StringTok{"91{-}100"}\NormalTok{,}\StringTok{"101{-}110"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Now, lets create the frequency table that shows the following: (1.) the frequency of deaths based on age ranges; (2.) Cumulative frequency of deaths; and (3.) proportions of deaths falling in those age ranges.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{freqtable }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{Bins)}
\CommentTok{\# see frequency of deaths by age Bins (i.e., age group only)}
\NormalTok{freqtable}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##     <20   21-30   31-40   41-50   51-60   61-70   71-80   81-90  91-100 101-110 
##     855    2725    2474    1606     911     378     122      41       5       2
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# now, add the cumulative frequency and proportion to get table output in RStudio}
\NormalTok{Output }\OtherTok{\textless{}{-}} \FunctionTok{transform}\NormalTok{(freqtable, }\AttributeTok{CumuFreq =} \FunctionTok{cumsum}\NormalTok{(Freq), }\AttributeTok{Proportions=}\FunctionTok{prop.table}\NormalTok{(Freq))}
\CommentTok{\# see final output}
\NormalTok{Output}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       Var1 Freq CumuFreq  Proportions
## 1      <20  855      855 0.0937602807
## 2    21-30 2725     3580 0.2988266257
## 3    31-40 2474     6054 0.2713016778
## 4    41-50 1606     7660 0.1761158022
## 5    51-60  911     8571 0.0999013050
## 6    61-70  378     8949 0.0414519136
## 7    71-80  122     9071 0.0133786599
## 8    81-90   41     9112 0.0044961070
## 9   91-100    5     9117 0.0005483057
## 10 101-110    2     9119 0.0002193223
\end{verbatim}

\textbf{Interpretation}: Fatal encounters with the police were more pronounced in victims (i.e., suspect or civilian) of the following age bracket: \texttt{21-30\ years\ (2,725,\ 29.8\%)}, \texttt{31-40\ years\ (2,474,\ 27.1\%)} and \texttt{41-50\ years\ (1,606,\ 17.6\%)}.

\hypertarget{using-a-barplot-and-piechart}{%
\subsection{\texorpdfstring{Using a \texttt{barplot()} and \texttt{piechart()}}{Using a barplot() and piechart()}}\label{using-a-barplot-and-piechart}}

Visually, the above bins or categories for the frequencies by age group can easily be represented using a \texttt{barplot()} or a \texttt{piechart()}. This code demonstrates how to create a barplot in RStudio:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# capture the values from table(). }
\NormalTok{tableAgeGroups }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{Bins)}
\CommentTok{\# feed the tableAgeGroups into barplot() function}
\FunctionTok{barplot}\NormalTok{(tableAgeGroups, }
        \AttributeTok{ylab =} \StringTok{"Age (in years)"}\NormalTok{, }
        \AttributeTok{main =} \StringTok{"Fatal Encounters: Age distributions"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{GEOG0125_files/figure-latex/unnamed-chunk-10-1.pdf}

This code also demonstrates how to create a piechart in RStudio:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Pie Chart with Percentages}
\CommentTok{\# capture the values from table(). }
\NormalTok{tableAgeGroups }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{Bins)}
\CommentTok{\# create vector for labelling pie chart}
\NormalTok{labels }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"\textless{}20"}\NormalTok{,}\StringTok{"21{-}30"}\NormalTok{,}\StringTok{"31{-}40"}\NormalTok{,}\StringTok{"41{-}50"}\NormalTok{,}\StringTok{"51{-}60"}\NormalTok{,}\StringTok{"61{-}70"}\NormalTok{,}\StringTok{"71{-}80"}\NormalTok{,}\StringTok{"81{-}90"}\NormalTok{,}\StringTok{"91{-}100"}\NormalTok{,}\StringTok{"101{-}110"}\NormalTok{)}
\CommentTok{\# calculate percentage}
\NormalTok{pct }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(tableAgeGroups}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(tableAgeGroups)}\SpecialCharTok{*}\DecValTok{100}\NormalTok{)}
\NormalTok{lbls }\OtherTok{\textless{}{-}} \FunctionTok{paste}\NormalTok{(labels, pct) }\CommentTok{\# add percents to labels }
\NormalTok{lbls }\OtherTok{\textless{}{-}} \FunctionTok{paste}\NormalTok{(lbls,}\StringTok{"\%"}\NormalTok{,}\AttributeTok{sep=}\StringTok{""}\NormalTok{) }\CommentTok{\# ad \% to labels }
\FunctionTok{pie}\NormalTok{(tableAgeGroups,}\AttributeTok{labels =}\NormalTok{ lbls, }\AttributeTok{col=}\FunctionTok{rainbow}\NormalTok{(}\FunctionTok{length}\NormalTok{(lbls)),}
   \AttributeTok{main=}\StringTok{"Fatal Encounters: Age distributions"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{GEOG0125_files/figure-latex/unnamed-chunk-11-1.pdf}

\hypertarget{descriptive-analysis-using-measures-for-central-tendency-dispersion}{%
\section{Descriptive analysis using measures for central tendency \& dispersion}\label{descriptive-analysis-using-measures-for-central-tendency-dispersion}}

\hypertarget{summary-estimates-using-summary}{%
\subsection{\texorpdfstring{Summary estimates using \texttt{summary()}}{Summary estimates using summary()}}\label{summary-estimates-using-summary}}

The \textbf{central tendency} refers to the tendency for the values of a continuous variable to be clustered round its mean or median. The arithmetic \textbf{mean} is a useful measure to describe this central tendency especially in the case when data is normally distributed. While the \textbf{median} is best for describing data when its skewed.

Dispersion on the other hand refers to the extent of how the distribution of the data either stretched or squeezed. The term is also interchangeable with words \textbf{variability}, \textbf{scatter}, or \textbf{spread}.

Computing these measures in RStudio are incredibly easy. Here's a list of functions and what they do:

\begin{itemize}
\tightlist
\item
  \texttt{mean()}: this calculates the average value (central measure)
\item
  \texttt{median()}: this calculates the middle-most value (or data point at the 50th percentile) (central measure)
\item
  \texttt{min()}: this finds the lowest value in the distribution (dispersion/range value)
\item
  \texttt{max()}: this finds the highest value in the distribution (dispersion/range value)
\item
  \texttt{IQR()}: this calculates the interquartile range by taking the difference using 25th- from 75th percentile values (dispersion/range)
\item
  \texttt{var()}: this calculates the variance - square root the value to get standard deviation (variability measure)
\item
  \texttt{sd()}: this calculates the standard deviation (variability measure)
\end{itemize}

You can use the above functions especially if you need to tease out a particular value if you are writing a recursive function. But you can easily compute these summary statistics simply by using the \texttt{summary()} code. Let's obtain the central tendency and range values for the only continuous variable in the data set which is the \texttt{Age} column.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# compute summary() function to get central and range values}
\FunctionTok{summary}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{Age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   10.00   26.00   34.00   36.44   45.00  107.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# compute the standard deviation sd()}
\FunctionTok{sd}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{Age)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 13.7431
\end{verbatim}

\textbf{Interpretation}: The overall average age of someone being killed due to a fatal encounter with the police in America is \texttt{36.44\ {[}sd\ of\ ±13.74,\ range:\ 10\ (minimum)\ to\ 107\ (maximum){]}} years, with IQRs between \texttt{26-45} years of age.

\hypertarget{using-a-boxplot-and-hist}{%
\subsection{\texorpdfstring{Using a \texttt{boxplot()} and \texttt{hist()}}{Using a boxplot() and hist()}}\label{using-a-boxplot-and-hist}}

Visually, the above summary estimates can easily be represented using a box plot. You can use this \texttt{boxplot()} to create the desired output:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# creates a boxplot(). This reproduces the estimates from summary() but graphically}
\FunctionTok{boxplot}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{Age, }
        \AttributeTok{ylab =} \StringTok{"Age (in years)"}\NormalTok{, }
        \AttributeTok{main =} \StringTok{"Fatal Encounters: Age distributions"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{GEOG0125_files/figure-latex/unnamed-chunk-13-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# creates a hist() this shows the shape of the age distribution}
\FunctionTok{hist}\NormalTok{(FatalEncounters}\SpecialCharTok{$}\NormalTok{Age, }
        \AttributeTok{ylab =} \StringTok{"Frequency"}\NormalTok{, }\AttributeTok{xlab =} \StringTok{"\textasciigrave{}Age (in years)"}\NormalTok{,}
        \AttributeTok{main =} \StringTok{"Fatal Encounters: Age distributions"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{GEOG0125_files/figure-latex/unnamed-chunk-14-1.pdf}

\hypertarget{generating-tables-shells-in-rstudio}{%
\section{Generating tables shells in RStudio}\label{generating-tables-shells-in-rstudio}}

There are a lot of categorical variables in this data set e.g., \texttt{Gender}, \texttt{LethalForceType}, \texttt{ArmedStatus}, \texttt{FleeingStatus}, \texttt{AggressionSign} and \texttt{Ethnicity}. You can generate custom made tables in RStudio saving you a whole bunch of time creating them in Word document. You can create them in R and export the result to word to make further modifications. You can install the package \texttt{gtsummary} and \texttt{dplyr}

\begin{itemize}
\tightlist
\item
  \texttt{gtsummary}: provides functions for making tables from RStudio and pasted into a document
\item
  \texttt{dplyr}: provides access to further data management functions
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# install.package()}
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"gtsummary"}\NormalTok{)}
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"dplyr"}\NormalTok{)}
\CommentTok{\# activate package}
\FunctionTok{library}\NormalTok{(}\StringTok{"gtsummary"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{"dplyr"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Installing the \texttt{gtsummary} package gives us access to the \texttt{tbl\_summary()} function which is a brilliant function to performing descriptive analyses and churning the results out in to a table from RStudio. The coding is quite involved though because it uses a bit of \texttt{tidyverse} syntax.

Let's create a table report only numbers by categories to get the basic ideas of the coding style:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# step 1: list of the variables you want to be generated in the table in the select() function for the original data.frame}
\CommentTok{\# step 2: pipe (\%\textgreater{}\%) into a new object called tableOutput}
\CommentTok{\# step 3: view tableOutput with tbl\_summary() function}

\NormalTok{tableOutput }\OtherTok{\textless{}{-}}\NormalTok{ FatalEncounters }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(Age, AggressionSign, ArmedStatus, Gender, Ethnicity, FleeingStatus, LethalForceType)}
\NormalTok{tableOutput }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{tbl\_summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

The result will appear in the \texttt{Viewer} window. For further exploration, we can perform a descriptive analysis for the demographic characteristics of the victims with their \texttt{Gender}, \texttt{Age} and \texttt{Ethnicity} broken down by type of lethal force used (i.e., \texttt{LethalForceType}) as an outcome. The outcome variable will be used as the split variable in the \texttt{by=} argument.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# example {-}{-}{-} update tableOutput to lethalforcetype, gender, age, skin colour \& include by=\textquotesingle{}LethalForceType\textquotesingle{}}
\NormalTok{tableOutput }\OtherTok{\textless{}{-}}\NormalTok{ FatalEncounters }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(Age, Gender, Ethnicity, LethalForceType)}
\NormalTok{tableOutput }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{tbl\_summary}\NormalTok{(}\AttributeTok{by=}\NormalTok{LethalForceType)}
\end{Highlighting}
\end{Shaded}

You can copy the table generated in RStudio's viewer directly and paste it into a Word document, and make the further modifications.

\begin{center}\includegraphics[width=1\linewidth]{/Volumes/Anwar-HHD/GEOG0125/Practicals/2021_2022/images/general/tableExport} \end{center}

\hypertarget{questions}{%
\section{Questions}\label{questions}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What do you think about the results displayed in the frequency table?
\item
  What conclusion do you draw from this table?
\end{enumerate}

Critical thinking: Discuss among yourselves whether the information provided in the final table is sufficient to make the conclusions in Question 2.

\hypertarget{parametric-and-nonparametric-tests}{%
\chapter{Parametric and Nonparametric Tests}\label{parametric-and-nonparametric-tests}}

\textbf{Theme: Cardiopulmonary System}

\begin{center}\includegraphics[width=1\linewidth]{/Volumes/Anwar-HHD/GEOG0125/Practicals/2021_2022/images/general/Cardiopulmonary_image} \end{center}

\hypertarget{introduction-1}{%
\section{Introduction}\label{introduction-1}}

This week we will learn how to perform hypothesis testing on a dataset containing additional health information on 654 individuals from aged 50+ years. This data is an ``altered'' excerpt extracted from the \href{https://www.cprd.com}{\textbf{Clinical Practice Research Datalink (CPRD)}} in 2014/15. The blood pressure and lung capacity readings are additional health outcomes that are routinely recorded by GP practices and logged into the CPRD database. An individual becomes at risk of these outcomes with the advancement of age, and especially when one enters the age bracket of 50s. We will carry out a series of basic hypothesis tests to examine which demographic and environmental risk factors effect these outcomes.At the end of this session, you should be able to perform the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  You will know how the null and alternative hypothesis should be framed.
\item
  You will be able to test the assumptions for parametric test
\item
  You will know how to select the appropriate statistical test
\item
  You will know how to interpret the p-values \& accept or reject of null hypothesis.
\end{enumerate}

\hypertarget{downloadable-dataset-for-this-exercise-1}{%
\subsection{Downloadable dataset for this exercise}\label{downloadable-dataset-for-this-exercise-1}}

Make sure to download the data set for Week 1 from \href{https://github.com/UCLPG-MSC-SGDS/GEOG0125/raw/main/Dataset.zip}{\textbf{HERE}}. The data file is named \texttt{WK02\ -\ Lung\ \&\ BP\ Data.csv}. Here is the data descriptor:

\begin{longtable}[]{@{}ll@{}}
\toprule
\textbf{Variable Name} & \textbf{Description} \\
\midrule
\endhead
id & Unique identification number \\
age & Age (in years) \\
agegroup & Age groups'': \textless55 years'', ``55-59 years'' \& ``60+ years'' \\
gender & Sex: ``male'' \& ``female'' \\
altitudetype & Residing on ``lowland'' or ``highland'' \\
initialBP & Initial systolic blood pressure reading \\
postBP & Post systolic blood pressure reading \\
initialLCV & Initial lung capacity air reading \\
folllowupLCV & Post lung capacity air reading \\
\bottomrule
\end{longtable}

\hypertarget{reading-list-1}{%
\subsection{Reading list}\label{reading-list-1}}

Please find reading list for this week:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Recommended Book: Dalgaard, P. (2008). \textbf{Introductory Statistics with R (Second Edition)}. Chapter 5: One- and two-sample tests. Pages 95 to 107 \href{https://link.springer.com/book/10.1007/978-0-387-79054-1}{(\textbf{Download Ebook here})}
\item
  Recommended Book: Dalgaard, P. (2008). \textbf{Introductory Statistics with R (Second Edition)}. Chapter 7: Analysis of variance and the Kruskal-Wallis test. Pages 127 to 143 \href{https://link.springer.com/book/10.1007/978-0-387-79054-1}{(\textbf{Download Ebook here})}
\end{enumerate}

\hypertarget{some-data-managing-ettiquttes}{%
\section{Some data managing ettiquttes}\label{some-data-managing-ettiquttes}}

Let us begin by importing the week 2 data set into RStudio. Let's call the data frame \texttt{healthdata}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Set your own directory using setwd() function}
\CommentTok{\# Load data into RStudio using read.csv(). The spreadsheet is stored in the object called \textquotesingle{}healdata\textquotesingle{}}
\NormalTok{healthdata }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"WK02 {-} Lung \& BP Data.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{logical-operators}{%
\subsection{Logical Operators}\label{logical-operators}}

Before we start, let us take a quick detour and cover some logical operators that can be used to make a set of conditions in R:

\begin{itemize}
\item
  The symbol \texttt{\textless{}} mean quantity is less than something
\item
  The symbol \texttt{\textless{}=} mean a quantity is less than and equal to something
\item
  The symbol \texttt{\textgreater{}} mean a quantity is greater than to something
\item
  The symbol \texttt{\textgreater{}=} mean a quantity is greater than and equal to something
\item
  The symbol \texttt{==} mean exactly identical to something
\item
  The symbol \texttt{!=} mean not identical to something
\item
  The symbol \texttt{\&} means AND
\item
  The symbol \texttt{\textbar{}} mean OR
\item
  The symbol \texttt{\textasciitilde{}} is called a tilde. It is used for showing a relationship (e.g.~\texttt{x\textasciitilde{}y}, \texttt{cancer\ \textasciitilde{}\ lifestyle\ +\ hereditary\ +\ smokingstatus} and etc.)
\end{itemize}

The list of logical operators are useful if we want to apply conditional statements or subset of records based on certain characteristics of our data. Let see how we can use these logical operators to create a subset of data from the health dataset we loaded into R.

Suppose we want to create the health data set where the rows in the column for the gender only keeps values that are `male'. We use the \texttt{==} logical operator to perform this task:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{healthdata\_males }\OtherTok{\textless{}{-}}\NormalTok{ healthdata[healthdata}\SpecialCharTok{$}\NormalTok{gender}\SpecialCharTok{==}\StringTok{"male"}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\textbf{IMPORTANT NOTES}: \texttt{healthdata\_males} data frame is a new object of records corresponding to males only. The code \texttt{healthdata{[}rows,\ columns{]}} format; here, we are telling R to use the \texttt{healthdata} data frame and inside the square brackets of the code i.e.~\texttt{healthdata\$gender=="male"} it appears BEFORE the comma (on the left). We are telling R to select the variable gender and where in the row for gender to filter values that are exactly identical to \texttt{“male”}.

Suppose we want to create an object from the \texttt{healthdata} data frame where the rows in the column for age only keep values that are less than and equal to 55. We use the \texttt{\textless{}=} logical operator to perform this task:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{healthdata\_age55 }\OtherTok{\textless{}{-}}\NormalTok{ healthdata[healthdata}\SpecialCharTok{$}\NormalTok{age }\SpecialCharTok{\textless{}=} \DecValTok{55}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

We can create compound statements. For instance, suppose we want to create from the \texttt{healthdata} that keeps \texttt{"females"} and residing on \texttt{"high\ land"} only. We use both the \texttt{==} and \texttt{\&} logical operators to perform this task:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{FemLowLand }\OtherTok{\textless{}{-}}\NormalTok{ healthdata[healthdata}\SpecialCharTok{$}\NormalTok{gender }\SpecialCharTok{==} \StringTok{"female"} \SpecialCharTok{\&}\NormalTok{ healthdata}\SpecialCharTok{$}\NormalTok{altitude }\SpecialCharTok{==} \StringTok{"low land"}\NormalTok{,]}
\end{Highlighting}
\end{Shaded}

\hypertarget{hypothesis-testing-for-2-groups}{%
\section{Hypothesis testing for 2 groups}\label{hypothesis-testing-for-2-groups}}

Suppose we want to investigate the impact of attitude (i.e.~residing on high land or low land) on lung capacity measured at baseline, and to see whether the baseline lung capacity in the groups are \textbf{different or not}. It is definitely preferred to use a parametric test.

We first start by writing out the hypothesis statement which typically looks something like:

\begin{itemize}
\item
  \textbf{Null hypothesis (H0)}: The mean for the initial lung capacity by altitude (i.e.~low and high land) are EQUAL
\item
  \textbf{Alternative hypothesis (H1)}: The mean for the initial lung capacity by attitude (i.e.~low and high land) are NOT EQUAL
\end{itemize}

Then, we check the following assumptions to ensure that the use of a parametric test is valid. Here are the list of assumptions we should test:

\begin{itemize}
\item
  Is the main outcome a continuous variable (i.e., it exists as either an interval or ratio variable)?
\item
  Is the sample size of group has \texttt{n\ ≥\ 30}?
\item
  Are there any outliers present for each group?
\item
  Is the outcome from a Gaussian (aka normal distribution) for each group?
\item
  Are the variances equal variances?
\end{itemize}

If any of the above assumptions are violated - you will need to use a nonparametric test.

\hypertarget{assumption-checking}{%
\subsection{Assumption checking}\label{assumption-checking}}

\textbf{Assumption 1}: Is the main outcome a continuous variable (i.e., it exists as either an interval or ratio variable)?

\textbf{Answer}: Yes, the initial lung capacity outcome variable (\texttt{initialLCV}) is an example of a ratio variable, with independent groups (i.e., s\texttt{altitude} variable)

\textbf{Assumption 2}: For each group, is n \textgreater{} 30?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# tabulate to see the number of individuals for each group}
\FunctionTok{table}\NormalTok{(healthdata}\SpecialCharTok{$}\NormalTok{altitude)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## high land  low land 
##        65       589
\end{verbatim}

\textbf{Answer}: Yes, both groups are above 30

\textbf{Assumption 3}: Are there any outliers presence for each group?

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# generate boxplots for each group and visualise in same plot window}
\FunctionTok{boxplot}\NormalTok{(healthdata}\SpecialCharTok{$}\NormalTok{initialLCV }\SpecialCharTok{\textasciitilde{}}\NormalTok{ healthdata}\SpecialCharTok{$}\NormalTok{altitude, }\AttributeTok{xlab =} \StringTok{"Altitude type"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Baseline LCV"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{GEOG0125_files/figure-latex/unnamed-chunk-25-1.pdf}

\textbf{Answer}: For the \texttt{high\ land} category is looks OK. For the \texttt{low\ land} category, the initial lung capacity outcome variable (\texttt{initialLCV}) seems to be marginally dispersed. We can turn a blind eye on this one and assume that the outliers are minor here. For this assumption, we can say its not violated.

\textbf{Assumption 4}: Are the data from each of the 2 groups follow a normal distribution? Here, use the Kolmogorov-Smirnov test's test to see if the p-value is above 0.05. We have chosen this over the Shapiro-Wilk's test because we are dealing with a large sample \texttt{n\ \textgreater{}\ 50} for both groups. This would mean that the distribution of the data is normal. This assumption is strict.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{groupHigh }\OtherTok{\textless{}{-}}\NormalTok{ healthdata}\SpecialCharTok{$}\NormalTok{initialLCV[healthdata}\SpecialCharTok{$}\NormalTok{altitude}\SpecialCharTok{==} \StringTok{"high land"}\NormalTok{]}
\NormalTok{groupLow }\OtherTok{\textless{}{-}}\NormalTok{ healthdata}\SpecialCharTok{$}\NormalTok{initialLCV[healthdata}\SpecialCharTok{$}\NormalTok{altitude}\SpecialCharTok{==} \StringTok{"low land"}\NormalTok{]}

\CommentTok{\# K{-}S normality test for "high land" }
\FunctionTok{ks.test}\NormalTok{(groupHigh, }\StringTok{"pnorm"}\NormalTok{, }\AttributeTok{mean=}\FunctionTok{mean}\NormalTok{(groupHigh), }\AttributeTok{sd=}\FunctionTok{sd}\NormalTok{(groupHigh)) }

\CommentTok{\# K{-}S normality test for "low land" }
\FunctionTok{ks.test}\NormalTok{(groupLow, }\StringTok{"pnorm"}\NormalTok{, }\AttributeTok{mean=}\FunctionTok{mean}\NormalTok{(groupLow), }\AttributeTok{sd=}\FunctionTok{sd}\NormalTok{(groupLow))}
\end{Highlighting}
\end{Shaded}

\textbf{Answer}: The values for initial LCV are normal when altitude is \texttt{"high\ land"} with a \texttt{p-value\ =\ 0.5727\ \textgreater{}\ 0.05}. However, its not normal when altitude is \texttt{"low\ land"} (i.e., \texttt{p-value\ =\ 0.043\ \textless{}\ 0.05} very marginal). Therefore, this assumption has been violated.

Ideally, we stop here and proceed with using a nonparametric test. But, nevertheless, here is how you test the last assumption.

\textbf{Assumption 5}: Do the two populations have the same variances? Here, use the F-test to see if the p-value is above 0.05. This would mean that the two group's variance's are the same. This assumption is also a strict assumption to test if the the fourth one passes.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var.test}\NormalTok{(healthdata}\SpecialCharTok{$}\NormalTok{initialLCV }\SpecialCharTok{\textasciitilde{}}\NormalTok{ healthdata}\SpecialCharTok{$}\NormalTok{altitude, }\AttributeTok{data =}\NormalTok{ healthdata)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  healthdata$initialLCV by healthdata$altitude
## F = 0.77756, num df = 64, denom df = 588, p-value = 0.2094
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.5533558 1.1540197
## sample estimates:
## ratio of variances 
##          0.7775639
\end{verbatim}

\textbf{Answer}: Yes, the population has equal variance and because the spread in the data is somewhat reflected in the boxplots, and the \texttt{p-value\ =\ 0.2094\ \textgreater{}\ 0.05}.

\hypertarget{selection-of-tests}{%
\subsection{Selection of tests}\label{selection-of-tests}}

\textbf{Statistical tests for Parametric and Nonparametric tests}

\begin{center}\includegraphics[width=1\linewidth]{/Volumes/Anwar-HHD/GEOG0125/Practicals/2021_2022/images/general/TestLists} \end{center}

The assumption concerning normality was violated. We need to therefore choose a nonparametric approach. The structure of the data has two groups which are independent. The approach is a \textbf{Mann-Whitney test}.

\textbf{Important note}: There will be a slight modification to the hypothesis statement since we will be performing the analysis within a nonparametric framework. Instead using the term \textbf{mean}, we instead use \textbf{medians}:

\begin{itemize}
\item
  \textbf{Null hypothesis (H0)}: The median for the initial lung capacity by altitude (i.e.~low and high land) are EQUAL
\item
  \textbf{Alternative hypothesis (H1)}: The median for the initial lung capacity by attitude (i.e.~low and high land) are NOT EQUAL
\end{itemize}

Let's perform a Mann-Whitney test using the \texttt{wilcox.test()} with the following options \texttt{exact\ =\ FALSE} (to suppress an infuriatingly stupid buggy message) and \texttt{paired\ =\ FALSE}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mann{-}Whitney test for independent groups}
\FunctionTok{wilcox.test}\NormalTok{(healthdata}\SpecialCharTok{$}\NormalTok{initialLCV }\SpecialCharTok{\textasciitilde{}}\NormalTok{ healthdata}\SpecialCharTok{$}\NormalTok{altitude, }\AttributeTok{exact =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{paired =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  healthdata$initialLCV by healthdata$altitude
## W = 28686, p-value = 4.071e-11
## alternative hypothesis: true location shift is not equal to 0
\end{verbatim}

\textbf{Interpretation}: The~p-value~of the test is 6.712e-11 (very small), which is less than the threshold for deeming significance (i.e., p \textless{} 0.05). We can reject the null hypothesis that the baseline LCV in people living in high altitude areas are the same as those living on low altitude lands. We can therefore accept the alternative and conclude that there's significant difference of measured LCV between the groups.

\hypertarget{questions-1}{%
\subsection{Questions}\label{questions-1}}

Use a paired test to determine whether there are any significant difference between measure for lung capacity measured at baseline and follow-up.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  What is the null and alternative hypothesis?
\item
  What would be the appropriate statistical test for testing this hypothesis?
\item
  What is the interpretation and conclusions for this test?
\end{enumerate}

\hypertarget{hypothesis-testing-for-3-or-more-groups}{%
\section{Hypothesis testing for 3 or more groups}\label{hypothesis-testing-for-3-or-more-groups}}

Suppose we want to investigate the impact of age groups on lung capacity measured at baseline, and to see whether the baseline lung capacity in the groups are \textbf{different or same across the three age groups}.

Again, we aim to use a parametric test and hypothesis statement will read something like:

\begin{itemize}
\item
  \textbf{Null hypothesis (H0)}: The mean for the initial lung capacity across the different age groups are EQUAL
\item
  \textbf{Alternative hypothesis (H1)}: The mean for the initial lung capacity across the different age groups are DIFFERENT
\end{itemize}

\hypertarget{asssumption-checking}{%
\subsection{Asssumption Checking}\label{asssumption-checking}}

Again, we check the following assumptions to ensure that the use of a parametric test is valid. Here are the list of assumptions we should test:

\textbf{Assumption 1}: Is the main outcome a continuous variable? \textbf{CHECK}

\textbf{Assumption 2}: For each group, is n \textgreater{} 30? \textbf{CHECK}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# tabulate to see the number of individuals for each group}
\FunctionTok{table}\NormalTok{(healthdata}\SpecialCharTok{$}\NormalTok{agegroup)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   <55 years 55-59 years   60+ years 
##         130         407         117
\end{verbatim}

\textbf{Assumption 3}: Are there any outliers presence for each group? \textbf{CHECK}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# generate boxplots for each group and visualise in same plot window}
\FunctionTok{boxplot}\NormalTok{(healthdata}\SpecialCharTok{$}\NormalTok{initialLCV }\SpecialCharTok{\textasciitilde{}}\NormalTok{ healthdata}\SpecialCharTok{$}\NormalTok{agegroup, }\AttributeTok{xlab =} \StringTok{"Age Group"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Baseline LCV"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{GEOG0125_files/figure-latex/unnamed-chunk-31-1.pdf}

\textbf{Assumption 4}: Are the data from each of the 3 groups follow a normal distribution? \textbf{CHECK}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{group55less }\OtherTok{\textless{}{-}}\NormalTok{ healthdata}\SpecialCharTok{$}\NormalTok{initialLCV[healthdata}\SpecialCharTok{$}\NormalTok{agegroup}\SpecialCharTok{==} \StringTok{"\textless{}55 years"}\NormalTok{]}
\NormalTok{group55\_59 }\OtherTok{\textless{}{-}}\NormalTok{ healthdata}\SpecialCharTok{$}\NormalTok{initialLCV[healthdata}\SpecialCharTok{$}\NormalTok{agegroup}\SpecialCharTok{==} \StringTok{"55{-}59 years"}\NormalTok{]}
\NormalTok{group60plus }\OtherTok{\textless{}{-}}\NormalTok{ healthdata}\SpecialCharTok{$}\NormalTok{initialLCV[healthdata}\SpecialCharTok{$}\NormalTok{agegroup}\SpecialCharTok{==} \StringTok{"60+ years"}\NormalTok{]}

\CommentTok{\# K{-}S normality test for "\textless{}55 years" }
\FunctionTok{ks.test}\NormalTok{(group55less, }\StringTok{"pnorm"}\NormalTok{, }\AttributeTok{mean=}\FunctionTok{mean}\NormalTok{(group55less), }\AttributeTok{sd=}\FunctionTok{sd}\NormalTok{(group55less)) }

\CommentTok{\# K{-}S normality test for "55{-}59 years" }
\FunctionTok{ks.test}\NormalTok{(group55\_59, }\StringTok{"pnorm"}\NormalTok{, }\AttributeTok{mean=}\FunctionTok{mean}\NormalTok{(group55\_59), }\AttributeTok{sd=}\FunctionTok{sd}\NormalTok{(group55\_59)) }

\CommentTok{\# K{-}S normality test for "60+ years" }
\FunctionTok{ks.test}\NormalTok{(group60plus, }\StringTok{"pnorm"}\NormalTok{, }\AttributeTok{mean=}\FunctionTok{mean}\NormalTok{(group60plus), }\AttributeTok{sd=}\FunctionTok{sd}\NormalTok{(group60plus)) }
\end{Highlighting}
\end{Shaded}

\hypertarget{selection-of-tests-1}{%
\subsection{Selection of tests}\label{selection-of-tests-1}}

\textbf{Statistical tests for Parametric and Nonparametric tests}

\begin{center}\includegraphics[width=1\linewidth]{/Volumes/Anwar-HHD/GEOG0125/Practicals/2021_2022/images/general/TestLists} \end{center}

in this instance, all the assumptions were met. In this scenario, we therefore choose a parametric approach. The structure of the data has three groups which are also independent. This time the approach is going to be a \textbf{One-way ANOVA test}.

Let's perform a 1-way ANONA test using the \texttt{aov()} function. No options as the code is straight forward!

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Mann{-}Whitney test for independent groups}
\FunctionTok{summary}\NormalTok{(}\FunctionTok{aov}\NormalTok{(healthdata}\SpecialCharTok{$}\NormalTok{initialLCV }\SpecialCharTok{\textasciitilde{}}\NormalTok{ healthdata}\SpecialCharTok{$}\NormalTok{agegroup))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                      Df Sum Sq Mean Sq F value Pr(>F)    
## healthdata$agegroup   2   2027  1013.3   275.8 <2e-16 ***
## Residuals           651   2392     3.7                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\textbf{Interpretation}: The~p-value~of the test is 2.2e-16 (very small), which is far less than the threshold for deeming statistical significance (i.e., p \textless{} 0.05). Hence, we can reject the null hypothesis that the baseline LCV in people across the three different age groups are similar. We therefore accept the alternative hypothesis and conclude that there's significant difference in the measured LCV across the age categories.

\hypertarget{questions-2}{%
\subsection{Questions}\label{questions-2}}

Use an unpaired test to determine whether there are any significant difference for baseline blood pressure measured across the three age groups:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  What is the null and alternative hypothesis?
\item
  What would be the appropriate statistical test for testing this hypothesis?
\item
  What is the interpretation and conclusions for this test?
\end{enumerate}

\hypertarget{conclusions}{%
\section{Conclusions}\label{conclusions}}

This is how hypothesis tests are carried out. Its very easy as you can see - the only tedious part is the assumptions testing. Be very strict when testing for normality especially, if this is violated, then go for the nonparametric test. So far, we have been performing two-tailed tests but you can conduct a one-tail test in your own time (see recommended readings).

Next week, we will learn more about multivariable regression models and the different families of models based on the outcome types.

\hypertarget{generalized-linear-models}{%
\chapter{Generalized Linear Models}\label{generalized-linear-models}}

\textbf{Theme: Crime, Livelihoods and Urban Poverty in Nigeria}

\begin{center}\includegraphics[width=1\linewidth]{/Volumes/Anwar-HHD/GEOG0125/Practicals/2021_2022/images/general/Vigilante group} \end{center}

\href{https://opendocs.ids.ac.uk/opendocs/bitstream/handle/20.500.12413/14390/R4PP_UrbanResilience.pdf?sequence=1\&isAllowed=y}{Photo: David Modugu; Malali Civilian JTF, Kaduna, Nigeria}

\hypertarget{introduction-2}{%
\section{Introduction}\label{introduction-2}}

This week we will learn how to perform generalised linear modelling to quantitative data focused on crime victimization in Africa. Context of our study: conventional analyses of crime, based on European research models, are often poorly suited to assessing the specific dimensions of criminality in Africa. the \href{https://www.urbantransformations.ox.ac.uk/project/development-frontiers-in-crime-livelihoods-and-urban-poverty-in-nigeria-fclp/}{\textbf{Development Frontiers in Crime, Livelihoods and Urban Poverty in Nigeria (FCLP)}} aims to provide an alternative framework for understanding the specific drivers of criminality in a West African urban context. This research project uses a mixed-methods approach for combining statistical modeling, geovisualisation and ethnography, and attempts to situates insecurity and crime against a broader backdrop of rapid urban growth, seasonal migration, youth unemployment and informality. The study typically provide researchers both in Nigeria and internationally with richer and more nuanced evidence base on the particular dynamics of crime in African cities.

In this practical, you will utilised the anoynmised data for the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Selection of the appropriate Poisson-based model for count or rate data
\item
  Interpretation of coefficients i.e., \textbf{Odds Ratios (OR)} and \textbf{Risk Ratios (RR)}
\item
  Running \texttt{glm()} for logistic regression model
\end{enumerate}

\hypertarget{downloadable-dataset-for-this-exercise-2}{%
\subsection{Downloadable dataset for this exercise}\label{downloadable-dataset-for-this-exercise-2}}

Make sure to download the data sets for Week 3 from \href{https://github.com/UCLPG-MSC-SGDS/GEOG0125/raw/main/Dataset.zip}{\textbf{HERE}}.

\hypertarget{reading-list-2}{%
\subsection{Reading list}\label{reading-list-2}}

Please find reading list for this week:

Recommended Book (sections): Dalgaard, P. (2008). \textbf{Introductory Statistics with R (Second Edition)}, \href{https://link.springer.com/book/10.1007/978-0-387-79054-1}{(\textbf{Download Ebook here})}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Chapter 12: Linear Models. Pages 195 to 224
\item
  Chapter 13: Logistic Regression. Pages 227 to 247
\item
  Chapter 15: Rates and Poisson regression. Pages 259 to 274
\end{enumerate}

\hypertarget{poisson-regression-modelling}{%
\section{Poisson Regression Modelling}\label{poisson-regression-modelling}}

Let's try out fitting a Poisson-type model some counts of households reporting to have been victims of burglary. Load the data into RStudio can call the object \texttt{burglaryDataset}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Set your own directory using setwd() function}
\CommentTok{\# Load data into RStudio using read.csv(). The spreadsheet is stored in the object called \textquotesingle{}burglaryData\textquotesingle{}}
\NormalTok{burglaryDataset }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"WK03 {-} Street Burglary Data in Nigeria.csv"}\NormalTok{)}
\FunctionTok{names}\NormalTok{(burglaryDataset)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "StreetID"         "Burglary"         "HousesVictim"     "denominators"    
##  [5] "connectivity"     "choice_q"         "integ_q"          "business_q"      
##  [9] "socioeconomic_q"  "log_denominators"
\end{verbatim}

\hypertarget{selecting-the-appropriate-poisson-model}{%
\subsection{Selecting the appropriate Poisson model}\label{selecting-the-appropriate-poisson-model}}

There are three different types of Poisson models, and implementation of one of these models are highly dependent on how the frequency distribution of the count response variable are displayed. If there is any evidence of over-dispersion, you are safe to use the \textbf{Negative Binomial Poisson regression}.

\begin{center}\includegraphics[width=1\linewidth]{/Volumes/Anwar-HHD/GEOG0125/Practicals/2021_2022/images/general/Plot_test_poisson} \end{center}

Let's check the frequency distribution of the outcome variable \texttt{Burglary} which corresponds to the number of reported instances a property on a street was burgled. You can simply use a histogram to examine its distribution:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{hist}\NormalTok{(burglaryDataset}\SpecialCharTok{$}\NormalTok{Burglary, }\AttributeTok{breaks=}\DecValTok{20}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{GEOG0125_files/figure-latex/unnamed-chunk-38-1.pdf}

The plot show evidence of over-dispersion. It indicates that streets in Kaduna have less frequency of burglaries. Here, we consider use a \textbf{Negative Binomial Poisson regression model} over the standard version (i.e., scenario 1). We will need to run the \texttt{glm.nb()} which can be accessed after installing the \texttt{MASS} package.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"MASS"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

We are going to fit the following risk factors for street accessibility (i.e., \texttt{distance}, \texttt{connectivity}, \texttt{closeness\ centrality} and \texttt{betweeness\ centrality}) as well as levels of commercial activity and socioeconomic status, to determine the level of risk of burglary victimisation and whether they are significantly associated with such burden of crime events.

Use the \texttt{glm.nb()} function:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_burglary }\OtherTok{\textless{}{-}} \FunctionTok{glm.nb}\NormalTok{(Burglary }\SpecialCharTok{\textasciitilde{}}\NormalTok{ connectivity }\SpecialCharTok{+} \FunctionTok{as.factor}\NormalTok{(choice\_q) }\SpecialCharTok{+} \FunctionTok{as.factor}\NormalTok{(integ\_q) }\SpecialCharTok{+} \FunctionTok{as.factor}\NormalTok{(business\_q) }\SpecialCharTok{+} \FunctionTok{as.factor}\NormalTok{(socioeconomic\_q), }\FunctionTok{offset}\NormalTok{(log\_denominators), }\AttributeTok{data =}\NormalTok{ burglaryDataset)}
\FunctionTok{summary}\NormalTok{(model\_burglary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## glm.nb(formula = Burglary ~ connectivity + as.factor(choice_q) + 
##     as.factor(integ_q) + as.factor(business_q) + as.factor(socioeconomic_q), 
##     data = burglaryDataset, weights = offset(log_denominators), 
##     init.theta = 0.4320699677, link = log)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7187  -1.5823  -1.0841   0.1554   5.2391  
## 
## Coefficients:
##                             Estimate Std. Error z value Pr(>|z|)    
## (Intercept)                 -0.22578    0.17902  -1.261  0.20723    
## connectivity                 0.06698    0.01459   4.589 4.45e-06 ***
## as.factor(choice_q)2         0.13299    0.14500   0.917  0.35905    
## as.factor(choice_q)3         0.45134    0.14555   3.101  0.00193 ** 
## as.factor(choice_q)4         0.43299    0.18946   2.285  0.02229 *  
## as.factor(integ_q)2         -0.38723    0.12962  -2.987  0.00281 ** 
## as.factor(integ_q)3         -0.19788    0.13159  -1.504  0.13265    
## as.factor(integ_q)4         -0.39527    0.14208  -2.782  0.00540 ** 
## as.factor(business_q)2      -0.19583    0.16607  -1.179  0.23832    
## as.factor(business_q)3      -0.26510    0.14751  -1.797  0.07231 .  
## as.factor(business_q)4       0.36246    0.14393   2.518  0.01179 *  
## as.factor(business_q)5       0.23496    0.14873   1.580  0.11415    
## as.factor(socioeconomic_q)2  0.12752    0.14055   0.907  0.36425    
## as.factor(socioeconomic_q)3 -0.05552    0.14288  -0.389  0.69758    
## as.factor(socioeconomic_q)4 -0.23991    0.14445  -1.661  0.09673 .  
## as.factor(socioeconomic_q)5 -0.11055    0.14526  -0.761  0.44661    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for Negative Binomial(0.4321) family taken to be 1)
## 
##     Null deviance: 1667.4  on 733  degrees of freedom
## Residual deviance: 1491.2  on 718  degrees of freedom
## AIC: 5163.5
## 
## Number of Fisher Scoring iterations: 1
## 
## 
##               Theta:  0.4321 
##           Std. Err.:  0.0268 
## 
##  2 x log-likelihood:  -5129.4770
\end{verbatim}

We the resulting estimates for the coefficient. Let extract the results for the coefficient and 95\% confidence interval, and convert them to \textbf{risk ratios (RR)} using the \texttt{exp()} function.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{estimates\_b }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(}\AttributeTok{Estimate =} \FunctionTok{coef}\NormalTok{(model\_burglary), }\FunctionTok{confint}\NormalTok{(model\_burglary))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Waiting for profiling to be done...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{IRR\_b }\OtherTok{\textless{}{-}} \FunctionTok{exp}\NormalTok{(estimates\_b)}
\CommentTok{\# report risk ratios (RRs) from NB model}
\CommentTok{\# estimates from model}
\NormalTok{IRR\_b}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                              Estimate     2.5 %    97.5 %
## (Intercept)                 0.7978901 0.5721526 1.1187344
## connectivity                1.0692691 1.0396767 1.1002334
## as.factor(choice_q)2        1.1422400 0.8623915 1.5124151
## as.factor(choice_q)3        1.5704135 1.1739365 2.1007452
## as.factor(choice_q)4        1.5418684 1.0534077 2.2604048
## as.factor(integ_q)2         0.6789374 0.5229902 0.8808479
## as.factor(integ_q)3         0.8204698 0.6222413 1.0818248
## as.factor(integ_q)4         0.6734948 0.4958594 0.9139292
## as.factor(business_q)2      0.8221517 0.5934210 1.1383763
## as.factor(business_q)3      0.7671307 0.5705697 1.0299236
## as.factor(business_q)4      1.4368589 1.0866198 1.8968155
## as.factor(business_q)5      1.2648633 0.9485132 1.6848248
## as.factor(socioeconomic_q)2 1.1360033 0.8588107 1.5019597
## as.factor(socioeconomic_q)3 0.9459926 0.7141379 1.2522731
## as.factor(socioeconomic_q)4 0.7866948 0.5864396 1.0541278
## as.factor(socioeconomic_q)5 0.8953407 0.6685331 1.1973841
\end{verbatim}

\textbf{Interpretation}:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Intercept:} Our model indicates an overall reduction in the occurrence for burglary by 21\% (Model Intercept: CRR 0.79, 95\% CI: 0.57--1.11) when all other risk factors show no influence. OR you can say it 0.79 times lower.
\item
  \textbf{Connectivity (cont.)}: For a unit increase in the number of connections on a street segment significantly increases the risk of burglaries by 6\% (CRR 1.06, 95\% CI: 1.03--1.10). or you can say the risk for burglaries in relation to a unit increase in the number of connections on a street are 1.06 times higher
\item
  \textbf{Betweenness centrality or ``Choice'' (cat.)}: Is strongly associated with an increased risk of victimization. It shows the risk of burglary is at least 57\% higher for residential properties located on street segments whose betweenness value falls in the 3rd (CRR: 1.57, 95\% CI: 1.17--2.10) and 4th quartile (CRR: 1.54, 95\% CI: 1.05--2.26) relative to the referent category.
\item
  \textbf{Closeness centrality or ``Integration'' (cat.)}: It shows an overall reduction in the risk of burglary regardless of the quartile categories for this variable. The relationship for here in particular appears unclear as the pattern for risk is akin to an inverted v-shape and so we cannot conclude something about this variable.
\end{enumerate}

\textbf{Question(s)}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  What would be the appropriate interpretation for the \textbf{Business activity index} and \textbf{Socioeconomic Status}
\end{enumerate}

\hypertarget{logistic-regression}{%
\section{Logistic Regression}\label{logistic-regression}}

Running a \texttt{glm()} for a logistic regression is very easy. As you will see when implementing it to the additional dataset we have provided. It has household-level information regarding the security status of a property. Here are the list of variables:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \texttt{Gate}: Is the property gated? (1 = yes, 0 = no)
\item
  \texttt{Garage}: Does the property contains a garage? (1 = yes, 0 = no)
\item
  \texttt{Outdoor\_sitting}: Does property have an outdoor sitting? (1 = yes, 0 = no)
\item
  \texttt{Security\_lights}: Are security lights attached to property? (1 = yes, 0 = no)
\item
  \texttt{TypeOFliving}: Categorised as a `Single', `Compound', `Extended' or `Person'
\item
  \texttt{BurglaryStatus}: Whether the household has been a victim of burglary (1 = yes, 0 = no) - outcome variable.
\end{enumerate}

Load the data \texttt{WK03\ -\ Household\ victimisation\ data\ in\ Nigeria.csv} and attempt to implement the \texttt{glm()} function on your own with the family option \texttt{binomial("logit")} specified accordingly. Make sure to use the \texttt{BurglaryStatus} variable as the dependent in the model.

\textbf{Question(s)}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  What would be the appropriate interpretation for the coefficients from this model.
\item
  Are we interpreting risk ratios or odds ratios?
\end{enumerate}

\hypertarget{introduction-to-bayesian-statistics}{%
\chapter{Introduction to Bayesian Statistics}\label{introduction-to-bayesian-statistics}}

\textbf{Theme: It's all about Bayes' Rule}

\begin{center}\includegraphics[width=1\linewidth]{/Volumes/Anwar-HHD/GEOG0125/Practicals/2021_2022/images/general/Bayes_Theorem_MMB_01} \end{center}

\hypertarget{introduction-3}{%
\section{Introduction}\label{introduction-3}}

This week's practical session is a unique one. You will be introduced to Bayesian Statistics. It is a branch of statistics which is steeped in probabilities and its interpretation. The core of Bayesian Statistics is the \textbf{Bayes' Theorem} (or \textbf{Bayes' Rule}) which uses conditional probabilities to quantify uncertainty surrounding the occurrence of events. In order to understand Bayesian Statistics, one should know the basic probability theory and how the Bayes' Rule works.

Let us begin.

\hypertarget{probability-theory}{%
\section{Probability theory}\label{probability-theory}}

In the lectures - we said that a probability is the language of uncertainty. It quantifies the uncertainty for a defined event which takes any value between 0 and 1, whereby an event with probabilities near zero implies an event to be very unlikely, and probabilities near one implies an event to be very likely.

\begin{itemize}
\item
  The notation for probabilities are \textbf{Pr( )} or \textbf{Prob( )}. We will be sticking with the notation for \textbf{Pr( )},
\item
  A probability is always a function of some event \textbf{\(E\)} which has a set number of outcomes as well as the sample space (or - population size) which is the total number of all possible outcomes that can occur for that event \textbf{\(E\)}
\item
  We can write this and say \textbf{Pr(\(E\))}, which is read as \textbf{``the probability that event \(E\) will occur''}
\end{itemize}

There are three types of probabilities:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Unconditional (or marginal) probabilities}: An unconditional probability (or marginal) is the chance (or likelihood) that a particular event (i.e., single) will occur without regards to external circumstances. For instance, we have a single event \textbf{\(E\)}. We therefore say, \textbf{Pr(\(E\))}, where we divide the number of observed outcomes \textbf{\(n\)} from \textbf{\(E\)} by the total sample space \textbf{\(N\)}. The formula for the unconditional probability \textbf{\(E\)} is \[Pr(E)= \frac{n}{N}\]
\item
  \textbf{Joint probabilities}: A joint probability deals with more than one event. When we have two events i.e., \textbf{\(E_1\)} and \textbf{\(E_2\)}, we say it is the chance that these two events will occur simultaneously at the same point in time. The notation for this is \textbf{Pr(\(E_1\) \& \(E_2\))}. The formula for joint probability of \textbf{\(E_1\)} and \textbf{\(E_2\)} is \[Pr(E_1 \& E_2) =  \frac{Pr(E_1 \cap E_2)}{N}\]
\item
  \textbf{Conditional probabilities}: A conditional probability of an event \textbf{\(E_1\)} is the probability that \textbf{\(E_1\)} will occur given the knowledge that an event \textbf{\(E_2\)} has already occurred. The notation for representing conditional probabilities uses \textbf{\textbar{}} symbol to represent something given, For instance, the probability of \textbf{\(E_1\)} given \textbf{\(E_2\)} is written as \textbf{Pr(\(E_1\) \textbar{} \(E_2\))}. Formula for conditional probability of \textbf{\(E_1\)} given \textbf{\(E_2\)} is \[Pr(E_1 | E_2) = \frac{Pr(E_1 \cap E_2)}{Pr(E_2)}\]
\end{enumerate}

\hypertarget{application-long-term-environmental-exposure-to-soil-arsenic-risk-of-metallic-poisoning.}{%
\subsection{Application: Long-term environmental exposure to soil arsenic \& risk of metallic poisoning.}\label{application-long-term-environmental-exposure-to-soil-arsenic-risk-of-metallic-poisoning.}}

Probabilities are used extensively in epidemiology to estimate the risk of a disease due to an exposure. When we say risk of a disease it simply means a probability. In fact, its with probabilities where we get relative risks (RRs) and odds ratios (ORs). Here is a scenario in a 2-by-2 table set in the context of environmental epidemiology.

\begin{longtable}[]{@{}llll@{}}
\toprule
Health Status & Poisoning & No Poisoning & Sum (row) \\
\midrule
\endhead
Exposed & 129 & 245 & 374 \\
Not Exposed & 171 & 332 & 503 \\
Sums (col) & 300 & 577 & 807 \\
\bottomrule
\end{longtable}

Health status of 807 residents in Cornwall, South West England, have been documented due to concentration levels of Arsenic in soil naturally exceeding the national UK safety limit (32 mg/kg). We can use the above data to compute the \textbf{unconditional}, \textbf{joint} and \textbf{conditional} probabilities for risk of metal toxicity.

First, let's write the notation to avoid any confusion:

\begin{itemize}
\item
  Let the health status \textbf{``poisoning''} represent \textbf{``p''}. Overall probability of \textbf{poisoning} is Pr(\(p\)). \textbf{``No poisoning''} is the complement of \textbf{``p''}, so let's represent this as \textbf{``p'''}. Hence, overall probability of \textbf{No poisoning} is written as Pr(\(p'\))
\item
  The following represents those who are exposed \textbf{``E''}. Overall probability of being \textbf{exposed} is Pr(\(E\)). Likewise, not being exposed is the complement of \textbf{``E''}. We can represent this as \textbf{``E'''}. Hence, overall probability of \textbf{Not exposed} is written as Pr(\(E'\))
\item
  We insert the corresponding notation into table to avoid confusion i.e., Pr( )
\end{itemize}

\begin{longtable}[]{@{}llll@{}}
\toprule
Health Status & Poisoning (\(p\)) & No Poisoning (\(p'\)) & Sum (row) \\
\midrule
\endhead
Exposed (\(E\)) & 129 {[}Pr(\(p \cap E\)){]} & 245 {[}Pr(\(p' \cap E\)){]} & 374 {[}Pr(\(E\)){]} \\
Not Exposed (\(E'\)) & 171 {[}Pr(\(p \cap E'\)){]} & 332 {[}Pr(\(p' \cap E'\)){]} & 503 {[}Pr(\(E'\)){]} \\
Sums (col) & 300 {[}Pr(\(p\)){]} & 577 {[}Pr(\(p'\)){]} & 807 {[}\(N\){]} \\
\bottomrule
\end{longtable}

\textbf{Unconditional probability} for metallic poisoning: Let the health status \textbf{``poisoning''} represent \textbf{``p''}. We can compute the unconditional probability Pr(\(p\)) as \[Pr(p)= \frac{n}{N} = \frac{300}{807} = 0.3717\]

The above estimate for Pr(\(p\)) = \texttt{37.17\%}. This probability estimate is proportion and in epidemiology we refer to this as a `\textbf{prevalence}'. Overall prevalence of metallic poisoning in Cornwall is \texttt{37.17\%}

What is the \textbf{joint probability} for those with the condition and at the same time exposed to elevated concentrations of soil arsenic? Here, let's represent those exposed with the notation Pr(\(E\)). We can compute the joint probability accordingly:

\[Pr(p \& E) =  \frac{Pr(p \cap E)}{N} = \frac{129}{807} = 0.1598\]

The above estimate for Pr(\(p \& E\)) = \texttt{15.98\%}. This is prevalence of metallic poisoning who are exposed.

What about the conditional probability i.e., the \textbf{likelihood} of having such chronic condition given that the person have been exposed? This can be computed accordingly as follows:

\[Pr(p | E) = \frac{Pr(p \cap E)}{Pr(E)} = \frac{(\frac{129}{807})}{(\frac{374}{807})} = 0.3449\]
The above estimate for Pr(\(p | E\)) = \texttt{34.49\%}. This is prevalence of metallic poisoning \textbf{given} being exposed.

\textbf{TASK}: Knowing what the types of probabilities untangles what the Bayes' theorem formula. Try to compute the \textbf{unconditional}, \textbf{joint} and \textbf{conditional} probabilities from the disease data set below:

\begin{longtable}[]{@{}llll@{}}
\toprule
Health Status & Diseased & Not Diseased & Sum (row) \\
\midrule
\endhead
Exposed & 5 & 10 & 15 \\
Not Exposed & 65 & 20 & 85 \\
Sums (col) & 70 & 30 & 100 \\
\bottomrule
\end{longtable}

Let's create a data frame to get you started:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Create data in a matrix}
\NormalTok{data }\OtherTok{\textless{}{-}}\FunctionTok{matrix}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{5}\NormalTok{, }\DecValTok{65}\NormalTok{, }\DecValTok{70}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{20}\NormalTok{, }\DecValTok{30}\NormalTok{, }\DecValTok{15}\NormalTok{, }\DecValTok{85}\NormalTok{, }\DecValTok{100}\NormalTok{),}\AttributeTok{nrow =} \DecValTok{3}\NormalTok{, }\AttributeTok{dimnames =} \FunctionTok{list}\NormalTok{(}\StringTok{"Exposure"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"Exposed"}\NormalTok{, }\StringTok{"Unexposed"}\NormalTok{, }\StringTok{"ColSum"}\NormalTok{), }\StringTok{"Status"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"Diseased"}\NormalTok{, }\StringTok{"Not Diseased"}\NormalTok{, }\StringTok{"RowSum"}\NormalTok{)))}

\NormalTok{data}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            Status
## Exposure    Diseased Not Diseased RowSum
##   Exposed          5           10     15
##   Unexposed       65           20     85
##   ColSum          70           30    100
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# You can extract the values from the martix by typing}

\NormalTok{data[}\DecValTok{1}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data[}\DecValTok{9}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 100
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#etc}
\end{Highlighting}
\end{Shaded}

\hypertarget{bayes-theorem}{%
\section{Bayes' Theorem}\label{bayes-theorem}}

The Bayes' theorem (or law) determines the conditional probability of a hypothesis (i.e., event) being true given the evidence (i.e., data). This allows us to express our belief in a particular hypothesis (\(H\)) or phenomenon, and how this believe should change after accounting for evidence (\(E\)) or data.

The Bayes' formula is:

\[Pr(H | E) = \frac{Pr(E|H)\cdot Pr(H)}{Pr(E)}\]
Description of each component: H is the hypothesis; Pr(\(H\)) is probability the hypothesis is true (before any evidence is present). This is the \textbf{prior}; Pr(\(E\)) is probability of observing the given hypothesis in light of the evidence; Pr(\(E|H\)) is the conditional probability of observing the data (i.e., evidence) given the hypothesis. Here, it indicates the compatibility between the data and hypothesis. This is our \textbf{likelihood}. Lastly, the Pr(\(H|E\)) is conditional probability i.e., what we want to know -- the probability of a hypothesis given after we observed the data. This is the \textbf{posterior} probability.

The expanded from of the formula is

\[Pr(H | E) = \frac{Pr(E|H)\cdot Pr(H)}{Pr(E|H) \cdot Pr(H) + Pr(E|H') \cdot Pr(H')}\]
Where,

\[Pr(E) = Pr(E|H) \cdot Pr(H) + Pr(E|H') \cdot Pr(H')\]

\hypertarget{applying-bayes-rule-on-the-metallic-poisoning-data}{%
\subsection{Applying Bayes' Rule on the metallic poisoning data}\label{applying-bayes-rule-on-the-metallic-poisoning-data}}

We believe that there 3 in 10 risk are poisoning with long-term exposure to elevated concentrations of arsenic from topsoil in Devon. In a previous survey in Cornwall, the prevalence was 35\%, granted that these findings are based on a similar setting with residents having similar exposure status. How probable would the risks be in Devon?

Prepare the model set-up:

\begin{itemize}
\tightlist
\item
  Prior: We hypotheses that there is 3 in 10 risk: \[Pr(H) = 3/10 = 0.3\]
\end{itemize}

\begin{itemize}
\tightlist
\item
  Likelihood: The prevalence is 35.0\% after observing the data if hypothesis is true: \[Pr(E | H) = 0.35\]
\end{itemize}

\begin{itemize}
\tightlist
\item
  Complements: \[Pr(H’) = 1 – 0.3 = 0.7; Pr(E | H’) = 1 – 0.35 = 0.65\]
\end{itemize}

\begin{itemize}
\tightlist
\item
  Posterior: \[Pr(H | E) = \frac{Pr(E|H)\cdot Pr(H)}{Pr(E|H) \cdot Pr(H) + Pr(E|H') \cdot Pr(H')} = \frac{0.35\cdot 0.3}{0.35 \cdot 0.3 + 0.7 \cdot 0.65} = 0.1875 = 18.75%
  \]
\end{itemize}

We can keep updating this belief by simply re-inserting the value for the new prevalence in Pr(\(H\)) and computing its complement i.e., Pr(\(H'\)).

\textbf{TASK}: Let's try to compute the \textbf{conditional} probability using the Bayes Rule with the example below. We suspect that the risk for contracting some disease is 3 in 15 although the prevalence for the disease could be as low as 20\% with exposure to its associated risk factors. What is Pr(\(H|E\))?

\hypertarget{bayesian-inference-with-probability-functions}{%
\section{Bayesian Inference with Probability Functions}\label{bayesian-inference-with-probability-functions}}

Bayes' Rule forms the crux of Bayesian inference. In this domain, we often rely on probability functions applied to the Bayes' rule to conduct parameter estimation for our hypothesis with the given the data. This process is somewhat tricky because you will need to derive a model for predicting the posterior distribution. The formula from the Bayes' Rule is the following: \[Pr(H | E) = \frac{Pr(E|H)\cdot Pr(H)}{Pr(E)} >> posterior \propto likelihood \cdot prior\]

As explained in the lecture, we simply remove the denominators (i.e., which is a constant term in this context) which, in turn, renders the relationship in the above equation to be proportional.With minimal information, it is possible to estimate a parameter through probabilistic modelling using this relation. Here, is an example.

\hypertarget{bayesian-inference-with-binomial-beta-distribution}{%
\subsection{Bayesian inference with Binomial-Beta distribution}\label{bayesian-inference-with-binomial-beta-distribution}}

Suppose, in a small survey, a random sample of 50 people from a large population at risk of arsenic poisoning due to environmental exposure status were selected. Each person's disease status was recorded as either \textbf{``Diseased''} or \textbf{``None''}. 19 of the respondents have found to be diseased and assign a Beta distribution with Beta(3,5). It is possible to predict the disease burden through Bayesian inference.

\begin{itemize}
\item
  Step 1: Let the proportion who are disease represent \(\theta\)
\item
  Step 2: Specify the model for the likelihood function. Here it is a Binomial function since we are dealing with proportions:
  \[\binom{50}{19}\theta^{19}(1-\theta)^{50-19}\]
\item
  Step 3: Specify the prior. Here, it's the Beta distribution with \(\alpha\) = 3 and \(\beta\) = 5. Its form is \[k\theta^{3-1}(1-\theta)^{5-1}\]
\item
  Step 4: Compute the posterior distribution by multiplying the binomial and beta functions together. All constant terms not having \(\theta\) can be thrown away:
\end{itemize}

\[(\theta^{19}(1-\theta)^{50-19}) \times (\theta^{3-1}(1-\theta)^{5-1})\]
\[\theta^{22-1}(1-\theta)^{36-1}\]
As you can see the posterior distribution is a Beta distribution, with the parameters updated from the binomial model. When the posterior is in the same family as the prior, we say the prior is a \textbf{conjugate} for the model. Here, the Beta prior is a conjugate for the binomial model. We can use this to estimate our parameter with the following code:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# set all possible values for theta }
\NormalTok{theta }\OtherTok{\textless{}{-}} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\AttributeTok{length =} \DecValTok{100}\NormalTok{)}
\CommentTok{\# compute the prior using the beta[3,5]}
\NormalTok{prior }\OtherTok{\textless{}{-}} \FunctionTok{dbeta}\NormalTok{(theta, }\DecValTok{3}\NormalTok{, }\DecValTok{5}\NormalTok{)}
\CommentTok{\# compute the posterior sample from updated formula which becomes a conjugate }
\NormalTok{posterior }\OtherTok{\textless{}{-}} \FunctionTok{dbeta}\NormalTok{(theta, }\DecValTok{22}\NormalTok{, }\DecValTok{36}\NormalTok{)}

\FunctionTok{plot}\NormalTok{(theta,posterior, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{max}\NormalTok{(posterior)}\SpecialCharTok{+}\DecValTok{1}\NormalTok{), }\AttributeTok{main =} \StringTok{"Posterior Probability (Prevalence)"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Posterior Density"}\NormalTok{, }\AttributeTok{xlab =} \FunctionTok{expression}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Probability of Parameter: "}\NormalTok{, theta, }\StringTok{" [\%]"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\includegraphics{GEOG0125_files/figure-latex/unnamed-chunk-45-1.pdf}

The mid-point of the posterior curve with the highest density is the posterior estimate we are looking for in predicting the disease burden, which is roughly \texttt{0.4}. Let's extract the estimate at \texttt{50\%} of this sample using the \texttt{qbeta()} function. We can also extract the point on \texttt{2.5\%} and \texttt{97.5\%} to report the \texttt{95\%} credible intervals, and let make sure that this estimate is reflected in the graphical output.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# estimate mean 50\% and 95\% CrI with qbeta()}
\NormalTok{Mean }\OtherTok{\textless{}{-}} \FunctionTok{qbeta}\NormalTok{(}\FloatTok{0.5}\NormalTok{, }\DecValTok{22}\NormalTok{, }\DecValTok{36}\NormalTok{)}
\NormalTok{LB }\OtherTok{\textless{}{-}} \FunctionTok{qbeta}\NormalTok{(}\FloatTok{0.025}\NormalTok{, }\DecValTok{22}\NormalTok{, }\DecValTok{36}\NormalTok{)}
\NormalTok{UB }\OtherTok{\textless{}{-}} \FunctionTok{qbeta}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\DecValTok{22}\NormalTok{, }\DecValTok{36}\NormalTok{)}

\NormalTok{Mean}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.377914
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{LB}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2599547
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{UB}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.506553
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot}\NormalTok{(theta,posterior, }\AttributeTok{ylim =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FunctionTok{max}\NormalTok{(posterior)}\SpecialCharTok{+}\DecValTok{1}\NormalTok{), }\AttributeTok{main =} \StringTok{"Posterior Probability (Prevalence)"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Posterior Density"}\NormalTok{, }\AttributeTok{xlab =} \FunctionTok{expression}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Probability of Parameter: "}\NormalTok{, theta, }\StringTok{" [\%]"}\NormalTok{)), }\AttributeTok{type=}\StringTok{"l"}\NormalTok{)}
\FunctionTok{segments}\NormalTok{(}\AttributeTok{x0=}\NormalTok{Mean, }\AttributeTok{y0=}\FunctionTok{max}\NormalTok{(posterior)}\SpecialCharTok{+}\DecValTok{1}\NormalTok{, }\AttributeTok{x1=}\NormalTok{Mean, }\AttributeTok{y1=}\DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \StringTok{"dashed"}\NormalTok{)}
\FunctionTok{segments}\NormalTok{(}\AttributeTok{x0=}\NormalTok{LB, }\AttributeTok{y0=}\FunctionTok{max}\NormalTok{(posterior)}\SpecialCharTok{+}\DecValTok{1}\NormalTok{, }\AttributeTok{x1=}\NormalTok{LB, }\AttributeTok{y1=}\DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \StringTok{"dashed"}\NormalTok{)}
\FunctionTok{segments}\NormalTok{(}\AttributeTok{x0=}\NormalTok{UB, }\AttributeTok{y0=}\FunctionTok{max}\NormalTok{(posterior)}\SpecialCharTok{+}\DecValTok{1}\NormalTok{, }\AttributeTok{x1=}\NormalTok{UB, }\AttributeTok{y1=}\DecValTok{0}\NormalTok{, }\AttributeTok{lty =} \StringTok{"dashed"}\NormalTok{)}
\FunctionTok{lines}\NormalTok{(theta,posterior, }\AttributeTok{col=}\StringTok{"red"}\NormalTok{, }\AttributeTok{lwd=}\DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{GEOG0125_files/figure-latex/unnamed-chunk-46-1.pdf}

\textbf{INTERPRETATION}: Combining this with the information from the binomial data, we get the posterior of Beta(\(\theta\), 22, 36). The above model's estimated prevalence is \texttt{37.79\%} with uncertainty of \texttt{25.9\%} to \texttt{50.6\%}

\textbf{TASK}: Try to derive the posterior model for a likelihood function with Poisson distribution and a prior with a gamma distribution. Multiple the two distribution and see if a conjugate is derived.

Poisson Distribution: \[P(Y|\theta) = \frac{\theta^{y}}{y!} \cdot e^{-\theta}\]

Gamma Distribution: \[P(\theta) = k\theta^{\alpha-1}\cdot e^{-\beta \cdot \theta}\]

\hypertarget{spatial-spatiotemporal-bayesian-models-using-inla}{%
\chapter{Spatial \& Spatiotemporal Bayesian Models using INLA}\label{spatial-spatiotemporal-bayesian-models-using-inla}}

\textbf{Theme: Road Accidents \& Casualties in the United Kingdom}

\begin{center}\includegraphics[width=1\linewidth]{/Volumes/Anwar-HHD/GEOG0125/Practicals/2021_2022/images/general/road_accident} \end{center}

\hypertarget{introduction-4}{%
\section{Introduction}\label{introduction-4}}

This week's practical you will be introduced to applying spatial \& spatiotemporal Bayesian models for the quantification of the risk of experiencing an outcome using R-INLA.

This exercise will focus on casualty data resulting from road accidents by car users (and/or occupants) in the UK. Road traffic accidents \& injuries are a serious problem worldwide. In fact, it is one of the leading causes of death attributed to significant life-years lost and as a consequence is associated with considerable economic losses to impacted individuals and families. There are many individual, environmental and geographical risk factors for road-related casualties. Here, we will use a series of spatial models from a Bayesian framework risks of casualties due to road accidents in local authority areas across the England.

\textbf{The learning objectives are:}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  How to implement the Spatial Conditional Autoregressive Model (CAR) to areal data that is not of a temporal structure.
\item
  How to extend the Spatial CAR to data that is of spatial and temporal structure.
\item
  For points 1 \& 2, how to predict the area-specific relative risks (RR) for areal units and how to determine whether the levels of risk are statistically significant through 95\% credible intervals (95\% CrI)
\item
  How to determination the Exceedance Probability i.e., the probability that an area has an excess risk of an outcome which exceeds a given threshold (e.g., say a RR \textgreater{} 1 (null value)).
\item
  How to make adjustments for other risk factors and model selection using with \texttt{CPO}, \texttt{DIC} and \texttt{WAIC}
\item
  Points 1 to 5 are scenarios which focus on outcomes following a Poisson process. Here, we will also demonstrate how spatial Bayesian models can be implemented to Binomial distributed outcomes as a special case for risk prediction (i.e., Odds Ratios (OR)).
\item
  Running \texttt{inla()} for spatial Bayesian modelling
\end{enumerate}

\hypertarget{downloadable-dataset-for-this-exercise-3}{%
\subsection{Downloadable dataset for this exercise}\label{downloadable-dataset-for-this-exercise-3}}

We will be using four different types of data sets for Week 8. Please download the following:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  The first data focuses purely on spatial data without a temporal structure. The data is titled: \texttt{Road\ Accidents\ in\ England\ 2015-2020\ NST.csv}. It contain overall counts of all fatal and serious casualties resulted from a car accident over the 6-year periods. The variables included are \texttt{lacode} (local authority), \texttt{gender} (Female or Male), \texttt{agegroup} (\texttt{1}= \texttt{20\ years\ \&\ below}, \texttt{2} = \texttt{21-35\ years}, \texttt{3} = \texttt{36-50\ years}, \texttt{4} = \texttt{51\ to\ 65\ years}, \texttt{5} = \texttt{66\ to\ 80\ years} and \texttt{6} = \texttt{81+\ years})
\item
  The second data is spatial the with the temporal structure. The data is titled: \texttt{Road\ Accidents\ in\ England\ 2015-2020\ ST.csv}. It contains all fatal and serious casualties resulted from a car accident broken down by each year from 2015 to 2020. It contains the same types of variables with addition to the \texttt{year} column.
\item
  \textbf{PLACE HOLDER FOR THIRD DATA}
\end{enumerate}

\hypertarget{recommended-reading-list}{%
\subsection{Recommended reading list}\label{recommended-reading-list}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Book: Moraga. P, (2020). \textbf{Geospatial Health Data: Modeling and Visualization with R-INLA \& Shiny}, \href{https://www.paulamoraga.com/book-geospatial/}{(\textbf{Link to Ebook})}
\end{enumerate}

\begin{itemize}
\item
  Chapter 5: Areal data
\item
  Chapter 6: Spatial modeling of areal data. Lip cancer in Scotland
\item
  Chapter 7: Spatio-temporal modeling of areal data. Lung cancer in Ohio
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Book: Blangiardo. M, \& Cameletti, M, (2015). \textbf{Spatial and Spatio-temporal Bayesian Models with R-INLA}. Wiley, ISBN: 978-1-118-32655-8. Access data sets \href{https://sites.google.com/a/r-inla.org/stbook/datasets}{HERE}. Download example R-codes \href{https://sites.google.com/a/r-inla.org/stbook/r-code}{HERE}
\end{enumerate}

\begin{itemize}
\item
  Chapter 6: Spatial Modeling (pages 173 to 234)
\item
  Chapter 7: Spatio-temporal models (pages 235 to 259)
\end{itemize}

\hypertarget{installing-and-loading-packages}{%
\section{Installing and loading packages}\label{installing-and-loading-packages}}

Here is the description of the following packages we will need for this exercise:

\begin{itemize}
\item
  \texttt{sf}: Simple Features
\item
  \texttt{tmap}: Thematic Mapping
\item
  \texttt{spdep}: Spatial Dependence (Weighting schemes \& Spatial Statistics)
\item
  \texttt{SpatialEpi}: Methods and data for cluster detection and disease mapping. We will use this for computing the expecting number for discrete outcomes
\item
  \texttt{INLA}: Package for performing a full Bayesian analysis of additive models using Integrated Nested Laplace approximation
\end{itemize}

You have already installed the packages \texttt{sf}, \texttt{tmap} \& \texttt{spdep} from previous sessions (i.e., \textbf{GEOG0114 Principles of Spatial Analysis}). Let us install the \texttt{INLA} and \texttt{SpatialEpi}packages.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# install the SpatialEpi}
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"SpatialEpi"}\NormalTok{)}

\CommentTok{\# install INLA package}
\FunctionTok{install.packages}\NormalTok{(}\StringTok{"INLA"}\NormalTok{,}\AttributeTok{repos=}\FunctionTok{c}\NormalTok{(}\FunctionTok{getOption}\NormalTok{(}\StringTok{"repos"}\NormalTok{),}\AttributeTok{INLA=}\StringTok{"https://inla.r{-}inla{-}download.org/R/stable"}\NormalTok{), }\AttributeTok{dep=}\ConstantTok{TRUE}\NormalTok{)}

\FunctionTok{library}\NormalTok{(}\StringTok{"SpatialEpi"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{"INLA"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{"sf"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{"tmap"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(}\StringTok{"spdep"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{loading-dataset}{%
\section{Loading dataset}\label{loading-dataset}}

Let us all quantitative data describe in section 5.1. into R/RStudio.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# set your own working directory setwd()}
\CommentTok{\# use read.csv() to import csv data}

\CommentTok{\# road accident data without temporal structure}
\NormalTok{road\_acc\_nontemp }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"Road Accidents in England 2015{-}2020 NST.csv"}\NormalTok{, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{sep =} \StringTok{","}\NormalTok{)}
\CommentTok{\# road accident data with temporal structure}
\NormalTok{road\_acc\_temp }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"Road Accidents in England 2015{-}2020 ST.csv"}\NormalTok{, }\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{sep =} \StringTok{","}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Let us all load the following shape files that we will need for today's analysis:

\begin{itemize}
\tightlist
\item
  Shape file: England's Regional borders named \texttt{England\ Regions\ Shapefile.shp}
\item
  Shape file: England's Local Authority borders (i.e., the unit of analysis) named \texttt{England\ Local\ Authority\ Shapefile.shp}
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Use read\_sf() function to load shape files }
\NormalTok{laboundaries }\OtherTok{\textless{}{-}} \FunctionTok{read\_sf}\NormalTok{(}\StringTok{"England Local Authority Shapefile.shp"}\NormalTok{)}
\NormalTok{regionboundaries }\OtherTok{\textless{}{-}} \FunctionTok{read\_sf}\NormalTok{(}\StringTok{"England Regions Shapefile.shp"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

The code chunk below generates an empty map for England's Local Authorities (LA) \& regions superimposed using the \texttt{tmap} functions.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tm\_shape}\NormalTok{(laboundaries) }\SpecialCharTok{+} \FunctionTok{tm\_polygons}\NormalTok{(}\AttributeTok{alpha =} \DecValTok{0}\NormalTok{, }\AttributeTok{border.alpha =} \FloatTok{0.3}\NormalTok{) }\SpecialCharTok{+} 
    \FunctionTok{tm\_shape}\NormalTok{(regionboundaries) }\SpecialCharTok{+} \FunctionTok{tm\_polygons}\NormalTok{(}\AttributeTok{alpha =} \DecValTok{0}\NormalTok{, }\AttributeTok{border.col =} \StringTok{"black"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{tm\_compass}\NormalTok{(}\AttributeTok{position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"top"}\NormalTok{)) }\SpecialCharTok{+} \FunctionTok{tm\_scale\_bar}\NormalTok{(}\AttributeTok{position =} \FunctionTok{c}\NormalTok{(}\StringTok{"right"}\NormalTok{, }\StringTok{"bottom"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics[width=1\linewidth]{/Volumes/Anwar-HHD/GEOG0125/Practicals/2021_2022/images/general/Image1_section5_3} \end{center}

  \bibliography{book.bib,packages.bib}

\end{document}
