<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Introduction to Bayesian Statistics | GEOG0125: Advanced Topics in Social Geographic Data Science</title>
  <meta name="description" content="4 Introduction to Bayesian Statistics | GEOG0125: Advanced Topics in Social Geographic Data Science Handbook" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Introduction to Bayesian Statistics | GEOG0125: Advanced Topics in Social Geographic Data Science" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="4 Introduction to Bayesian Statistics | GEOG0125: Advanced Topics in Social Geographic Data Science Handbook" />
  <meta name="github-repo" content="UCLPG-MSC-SGDS/GEOG0125" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Introduction to Bayesian Statistics | GEOG0125: Advanced Topics in Social Geographic Data Science" />
  
  <meta name="twitter:description" content="4 Introduction to Bayesian Statistics | GEOG0125: Advanced Topics in Social Geographic Data Science Handbook" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="generalized-linear-models.html"/>
<link rel="next" href="spatial-spatiotemporal-bayesian-models-using-inla.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="assets/custom.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo">
<a href="https://www.ucl.ac.uk/module-catalogue/modules/advanced-topics-in-social-and-geographic-data-science-GEOG0125"><img src="images/general/ucl_logo.png">
</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#moodle"><i class="fa fa-check"></i>Moodle</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure"><i class="fa fa-check"></i>Structure</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#office-hours-for-geog0125"><i class="fa fa-check"></i>Office hours for GEOG0125</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>1</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#downloadable-dataset-for-this-exercise"><i class="fa fa-check"></i><b>1.1.1</b> Downloadable dataset for this exercise</a></li>
<li class="chapter" data-level="1.1.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#reading-list"><i class="fa fa-check"></i><b>1.1.2</b> Reading list</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#frequency-distribution"><i class="fa fa-check"></i><b>1.2</b> Frequency distribution</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#computing-frequencies-cumulative-frequency-and-proportions"><i class="fa fa-check"></i><b>1.2.1</b> Computing frequencies, cumulative frequency and proportions</a></li>
<li class="chapter" data-level="1.2.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#using-a-barplot-and-piechart"><i class="fa fa-check"></i><b>1.2.2</b> Using a <code>barplot()</code> and <code>piechart()</code></a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#descriptive-analysis-using-measures-for-central-tendency-dispersion"><i class="fa fa-check"></i><b>1.3</b> Descriptive analysis using measures for central tendency &amp; dispersion</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summary-estimates-using-summary"><i class="fa fa-check"></i><b>1.3.1</b> Summary estimates using <code>summary()</code></a></li>
<li class="chapter" data-level="1.3.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#using-a-boxplot-and-hist"><i class="fa fa-check"></i><b>1.3.2</b> Using a <code>boxplot()</code> and <code>hist()</code></a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#generating-tables-shells-in-rstudio"><i class="fa fa-check"></i><b>1.4</b> Generating tables shells in RStudio</a></li>
<li class="chapter" data-level="1.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#questions"><i class="fa fa-check"></i><b>1.5</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html"><i class="fa fa-check"></i><b>2</b> Parametric and Nonparametric Tests</a>
<ul>
<li class="chapter" data-level="2.1" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#introduction-1"><i class="fa fa-check"></i><b>2.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#downloadable-dataset-for-this-exercise-1"><i class="fa fa-check"></i><b>2.1.1</b> Downloadable dataset for this exercise</a></li>
<li class="chapter" data-level="2.1.2" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#reading-list-1"><i class="fa fa-check"></i><b>2.1.2</b> Reading list</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#some-data-managing-ettiquttes"><i class="fa fa-check"></i><b>2.2</b> Some data managing ettiquttes</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#logical-operators"><i class="fa fa-check"></i><b>2.2.1</b> Logical Operators</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#hypothesis-testing-for-2-groups"><i class="fa fa-check"></i><b>2.3</b> Hypothesis testing for 2 groups</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#assumption-checking"><i class="fa fa-check"></i><b>2.3.1</b> Assumption checking</a></li>
<li class="chapter" data-level="2.3.2" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#selection-of-tests"><i class="fa fa-check"></i><b>2.3.2</b> Selection of tests</a></li>
<li class="chapter" data-level="2.3.3" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#questions-1"><i class="fa fa-check"></i><b>2.3.3</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#hypothesis-testing-for-3-or-more-groups"><i class="fa fa-check"></i><b>2.4</b> Hypothesis testing for 3 or more groups</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#asssumption-checking"><i class="fa fa-check"></i><b>2.4.1</b> Asssumption Checking</a></li>
<li class="chapter" data-level="2.4.2" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#selection-of-tests-1"><i class="fa fa-check"></i><b>2.4.2</b> Selection of tests</a></li>
<li class="chapter" data-level="2.4.3" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#questions-2"><i class="fa fa-check"></i><b>2.4.3</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="parametric-and-nonparametric-tests.html"><a href="parametric-and-nonparametric-tests.html#conclusions"><i class="fa fa-check"></i><b>2.5</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html"><i class="fa fa-check"></i><b>3</b> Generalized Linear Models</a>
<ul>
<li class="chapter" data-level="3.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#introduction-2"><i class="fa fa-check"></i><b>3.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#downloadable-dataset-for-this-exercise-2"><i class="fa fa-check"></i><b>3.1.1</b> Downloadable dataset for this exercise</a></li>
<li class="chapter" data-level="3.1.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#reading-list-2"><i class="fa fa-check"></i><b>3.1.2</b> Reading list</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#poisson-regression-modelling"><i class="fa fa-check"></i><b>3.2</b> Poisson Regression Modelling</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#selecting-the-appropriate-poisson-model"><i class="fa fa-check"></i><b>3.2.1</b> Selecting the appropriate Poisson model</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="generalized-linear-models.html"><a href="generalized-linear-models.html#logistic-regression"><i class="fa fa-check"></i><b>3.3</b> Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html"><i class="fa fa-check"></i><b>4</b> Introduction to Bayesian Statistics</a>
<ul>
<li class="chapter" data-level="4.1" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#introduction-3"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#probability-theory"><i class="fa fa-check"></i><b>4.2</b> Probability theory</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#application-long-term-environmental-exposure-to-soil-arsenic-risk-of-metallic-poisoning."><i class="fa fa-check"></i><b>4.2.1</b> Application: Long-term environmental exposure to soil arsenic &amp; risk of metallic poisoning.</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#bayes-theorem"><i class="fa fa-check"></i><b>4.3</b> Bayes’ Theorem</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#applying-bayes-rule-on-the-metallic-poisoning-data"><i class="fa fa-check"></i><b>4.3.1</b> Applying Bayes’ Rule on the metallic poisoning data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#bayesian-inference-with-probability-functions"><i class="fa fa-check"></i><b>4.4</b> Bayesian Inference with Probability Functions</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#bayesian-inference-with-binomial-beta-distribution"><i class="fa fa-check"></i><b>4.4.1</b> Bayesian inference with Binomial-Beta distribution</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html"><i class="fa fa-check"></i><b>5</b> Spatial &amp; Spatiotemporal Bayesian Models using INLA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#introduction-4"><i class="fa fa-check"></i><b>5.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#downloadable-dataset-for-this-exercise-3"><i class="fa fa-check"></i><b>5.1.1</b> Downloadable dataset for this exercise</a></li>
<li class="chapter" data-level="5.1.2" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#recommended-reading-list"><i class="fa fa-check"></i><b>5.1.2</b> Recommended reading list</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>5.2</b> Installing and loading packages</a></li>
<li class="chapter" data-level="5.3" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#loading-dataset"><i class="fa fa-check"></i><b>5.3</b> Loading dataset</a></li>
<li class="chapter" data-level="5.4" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#spatial-bayesian-modelling-non-temporal-data"><i class="fa fa-check"></i><b>5.4</b> Spatial Bayesian Modelling (Non-temporal data)</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#data-preparation"><i class="fa fa-check"></i><b>5.4.1</b> Data preparation</a></li>
<li class="chapter" data-level="5.4.2" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#creating-an-adjacency-matrix"><i class="fa fa-check"></i><b>5.4.2</b> Creating an adjacency matrix</a></li>
<li class="chapter" data-level="5.4.3" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#model-formation"><i class="fa fa-check"></i><b>5.4.3</b> Model formation</a></li>
<li class="chapter" data-level="5.4.4" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#bayesian-inference-using-inla"><i class="fa fa-check"></i><b>5.4.4</b> Bayesian inference using INLA</a></li>
<li class="chapter" data-level="" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#interpretation-of-the-overall-risks"><i class="fa fa-check"></i>Interpretation of the overall risks</a></li>
<li class="chapter" data-level="" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#mapping-the-relative-risks-rr-of-casualties-in-england"><i class="fa fa-check"></i>Mapping the Relative Risks (RR) of casualties in England</a></li>
<li class="chapter" data-level="" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#mapping-the-exceedance-probability-of-excess-risk-of-casualties-in-england"><i class="fa fa-check"></i>Mapping the Exceedance Probability of excess risk of casualties in England</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#spatiotemporal-bayesian-modelling"><i class="fa fa-check"></i><b>5.5</b> Spatiotemporal Bayesian Modelling</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#data-preparation-1"><i class="fa fa-check"></i><b>5.5.1</b> Data preparation</a></li>
<li class="chapter" data-level="5.5.2" data-path="spatial-spatiotemporal-bayesian-models-using-inla.html"><a href="spatial-spatiotemporal-bayesian-models-using-inla.html#model-formation-inference-with-inla"><i class="fa fa-check"></i><b>5.5.2</b> Model formation &amp; inference with INLA</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">GEOG0125: Advanced Topics in Social Geographic Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-to-bayesian-statistics" class="section level1" number="4">
<h1><span class="header-section-number">4</span> Introduction to Bayesian Statistics</h1>
<p><strong>Theme: It’s all about Bayes’ Rule</strong>
<img src="images/general/Bayes_Theorem_MMB_01.jpg" width="100%" style="display: block; margin: auto;" /></p>
<div id="introduction-3" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Introduction</h2>
<p>This week’s practical session is a unique one. You will be introduced to Bayesian Statistics. It is a branch of statistics which is steeped in probabilities and its interpretation. The core of Bayesian Statistics is the <strong>Bayes’ Theorem</strong> (or <strong>Bayes’ Rule</strong>) which uses conditional probabilities to quantify uncertainty surrounding the occurrence of events. In order to understand Bayesian Statistics, one should know the basic probability theory and how the Bayes’ Rule works.</p>
<p>Let us begin.</p>
</div>
<div id="probability-theory" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Probability theory</h2>
<p>In the lectures - we said that a probability is the language of uncertainty. It quantifies the uncertainty for a defined event which takes any value between 0 and 1, whereby an event with probabilities near zero implies an event to be very unlikely, and probabilities near one implies an event to be very likely.</p>
<ul>
<li><p>The notation for probabilities are <strong>Pr( )</strong> or <strong>Prob( )</strong>. We will be sticking with the notation for <strong>Pr( )</strong>,</p></li>
<li><p>A probability is always a function of some event <strong><span class="math inline">\(E\)</span></strong> which has a set number of outcomes as well as the sample space (or - population size) which is the total number of all possible outcomes that can occur for that event <strong><span class="math inline">\(E\)</span></strong></p></li>
<li><p>We can write this and say <strong>Pr(<span class="math inline">\(E\)</span>)</strong>, which is read as <strong>“the probability that event <span class="math inline">\(E\)</span> will occur”</strong></p></li>
</ul>
<p>There are three types of probabilities:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Unconditional (or marginal) probabilities</strong>: An unconditional probability (or marginal) is the chance (or likelihood) that a particular event (i.e., single) will occur without regards to external circumstances. For instance, we have a single event <strong><span class="math inline">\(E\)</span></strong>. We therefore say, <strong>Pr(<span class="math inline">\(E\)</span>)</strong>, where we divide the number of observed outcomes <strong><span class="math inline">\(n\)</span></strong> from <strong><span class="math inline">\(E\)</span></strong> by the total sample space <strong><span class="math inline">\(N\)</span></strong>. The formula for the unconditional probability <strong><span class="math inline">\(E\)</span></strong> is <span class="math display">\[Pr(E)= \frac{n}{N}\]</span></p></li>
<li><p><strong>Joint probabilities</strong>: A joint probability deals with more than one event. When we have two events i.e., <strong><span class="math inline">\(E_1\)</span></strong> and <strong><span class="math inline">\(E_2\)</span></strong>, we say it is the chance that these two events will occur simultaneously at the same point in time. The notation for this is <strong>Pr(<span class="math inline">\(E_1\)</span> &amp; <span class="math inline">\(E_2\)</span>)</strong>. The formula for joint probability of <strong><span class="math inline">\(E_1\)</span></strong> and <strong><span class="math inline">\(E_2\)</span></strong> is <span class="math display">\[Pr(E_1 \&amp; E_2) =  \frac{Pr(E_1 \cap E_2)}{N}\]</span></p></li>
<li><p><strong>Conditional probabilities</strong>: A conditional probability of an event <strong><span class="math inline">\(E_1\)</span></strong> is the probability that <strong><span class="math inline">\(E_1\)</span></strong> will occur given the knowledge that an event <strong><span class="math inline">\(E_2\)</span></strong> has already occurred. The notation for representing conditional probabilities uses <strong>|</strong> symbol to represent something given, For instance, the probability of <strong><span class="math inline">\(E_1\)</span></strong> given <strong><span class="math inline">\(E_2\)</span></strong> is written as <strong>Pr(<span class="math inline">\(E_1\)</span> | <span class="math inline">\(E_2\)</span>)</strong>. Formula for conditional probability of <strong><span class="math inline">\(E_1\)</span></strong> given <strong><span class="math inline">\(E_2\)</span></strong> is <span class="math display">\[Pr(E_1 | E_2) = \frac{Pr(E_1 \cap E_2)}{Pr(E_2)}\]</span></p></li>
</ol>
<div id="application-long-term-environmental-exposure-to-soil-arsenic-risk-of-metallic-poisoning." class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Application: Long-term environmental exposure to soil arsenic &amp; risk of metallic poisoning.</h3>
<p>Probabilities are used extensively in epidemiology to estimate the risk of a disease due to an exposure. When we say risk of a disease it simply means a probability. In fact, its with probabilities where we get relative risks (RRs) and odds ratios (ORs). Here is a scenario in a 2-by-2 table set in the context of environmental epidemiology.</p>
<p></br></p>
<table>
<thead>
<tr class="header">
<th>Health Status</th>
<th>Poisoning</th>
<th>No Poisoning</th>
<th>Sum (row)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exposed</td>
<td>129</td>
<td>245</td>
<td>374</td>
</tr>
<tr class="even">
<td>Not Exposed</td>
<td>171</td>
<td>332</td>
<td>503</td>
</tr>
<tr class="odd">
<td>Sums (col)</td>
<td>300</td>
<td>577</td>
<td>807</td>
</tr>
</tbody>
</table>
<p></br></p>
<p>Health status of 807 residents in Cornwall, South West England, have been documented due to concentration levels of Arsenic in soil naturally exceeding the national UK safety limit (32 mg/kg). We can use the above data to compute the <strong>unconditional</strong>, <strong>joint</strong> and <strong>conditional</strong> probabilities for risk of metal toxicity.</p>
<p>First, let’s write the notation to avoid any confusion:</p>
<ul>
<li><p>Let the health status <strong>“poisoning”</strong> represent <strong>“p”</strong>. Overall probability of <strong>poisoning</strong> is Pr(<span class="math inline">\(p\)</span>). <strong>“No poisoning”</strong> is the complement of <strong>“p”</strong>, so let’s represent this as <strong>“p’”</strong>. Hence, overall probability of <strong>No poisoning</strong> is written as Pr(<span class="math inline">\(p&#39;\)</span>)</p></li>
<li><p>The following represents those who are exposed <strong>“E”</strong>. Overall probability of being <strong>exposed</strong> is Pr(<span class="math inline">\(E\)</span>). Likewise, not being exposed is the complement of <strong>“E”</strong>. We can represent this as <strong>“E’”</strong>. Hence, overall probability of <strong>Not exposed</strong> is written as Pr(<span class="math inline">\(E&#39;\)</span>)</p></li>
<li><p>We insert the corresponding notation into table to avoid confusion i.e., Pr( )</p></li>
</ul>
<p></br></p>
<table>
<thead>
<tr class="header">
<th>Health Status</th>
<th>Poisoning (<span class="math inline">\(p\)</span>)</th>
<th>No Poisoning (<span class="math inline">\(p&#39;\)</span>)</th>
<th>Sum (row)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exposed (<span class="math inline">\(E\)</span>)</td>
<td>129 [Pr(<span class="math inline">\(p \cap E\)</span>)]</td>
<td>245 [Pr(<span class="math inline">\(p&#39; \cap E\)</span>)]</td>
<td>374 [Pr(<span class="math inline">\(E\)</span>)]</td>
</tr>
<tr class="even">
<td>Not Exposed (<span class="math inline">\(E&#39;\)</span>)</td>
<td>171 [Pr(<span class="math inline">\(p \cap E&#39;\)</span>)]</td>
<td>332 [Pr(<span class="math inline">\(p&#39; \cap E&#39;\)</span>)]</td>
<td>503 [Pr(<span class="math inline">\(E&#39;\)</span>)]</td>
</tr>
<tr class="odd">
<td>Sums (col)</td>
<td>300 [Pr(<span class="math inline">\(p\)</span>)]</td>
<td>577 [Pr(<span class="math inline">\(p&#39;\)</span>)]</td>
<td>807 [<span class="math inline">\(N\)</span>]</td>
</tr>
</tbody>
</table>
<p></br></p>
<p><strong>Unconditional probability</strong> for metallic poisoning: Let the health status <strong>“poisoning”</strong> represent <strong>“p”</strong>. We can compute the unconditional probability Pr(<span class="math inline">\(p\)</span>) as <span class="math display">\[Pr(p)= \frac{n}{N} = \frac{300}{807} = 0.3717\]</span></p>
<p>The above estimate for Pr(<span class="math inline">\(p\)</span>) = <code>37.17%</code>. This probability estimate is proportion and in epidemiology we refer to this as a ‘<strong>prevalence</strong>.’ Overall prevalence of metallic poisoning in Cornwall is <code>37.17%</code></p>
<p>What is the <strong>joint probability</strong> for those with the condition and at the same time exposed to elevated concentrations of soil arsenic? Here, let’s represent those exposed with the notation Pr(<span class="math inline">\(E\)</span>). We can compute the joint probability accordingly:</p>
<p><span class="math display">\[Pr(p \&amp; E) =  \frac{Pr(p \cap E)}{N} = \frac{129}{807} = 0.1598\]</span></p>
<p>The above estimate for Pr(<span class="math inline">\(p \&amp; E\)</span>) = <code>15.98%</code>. This is prevalence of metallic poisoning who are exposed.</p>
<p>What about the conditional probability i.e., the <strong>likelihood</strong> of having such chronic condition given that the person have been exposed? This can be computed accordingly as follows:</p>
<p><span class="math display">\[Pr(p | E) = \frac{Pr(p \cap E)}{Pr(E)} = \frac{(\frac{129}{807})}{(\frac{374}{807})} = 0.3449\]</span>
The above estimate for Pr(<span class="math inline">\(p | E\)</span>) = <code>34.49%</code>. This is prevalence of metallic poisoning <strong>given</strong> being exposed.</p>
<p><strong>TASK</strong>: Knowing what the types of probabilities untangles what the Bayes’ theorem formula. Try to compute the <strong>unconditional</strong>, <strong>joint</strong> and <strong>conditional</strong> probabilities from the disease data set below:</p>
<p></br></p>
<table>
<thead>
<tr class="header">
<th>Health Status</th>
<th>Diseased</th>
<th>Not Diseased</th>
<th>Sum (row)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Exposed</td>
<td>5</td>
<td>10</td>
<td>15</td>
</tr>
<tr class="even">
<td>Not Exposed</td>
<td>65</td>
<td>20</td>
<td>85</td>
</tr>
<tr class="odd">
<td>Sums (col)</td>
<td>70</td>
<td>30</td>
<td>100</td>
</tr>
</tbody>
</table>
<p></br></p>
<p>Let’s create a data frame to get you started:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="introduction-to-bayesian-statistics.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create data in a matrix</span></span>
<span id="cb56-2"><a href="introduction-to-bayesian-statistics.html#cb56-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">65</span>, <span class="dv">70</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">15</span>, <span class="dv">85</span>, <span class="dv">100</span>),<span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="st">&quot;Exposure&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Exposed&quot;</span>, <span class="st">&quot;Unexposed&quot;</span>, <span class="st">&quot;ColSum&quot;</span>), <span class="st">&quot;Status&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Diseased&quot;</span>, <span class="st">&quot;Not Diseased&quot;</span>, <span class="st">&quot;RowSum&quot;</span>)))</span>
<span id="cb56-3"><a href="introduction-to-bayesian-statistics.html#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="introduction-to-bayesian-statistics.html#cb56-4" aria-hidden="true" tabindex="-1"></a>data</span></code></pre></div>
<pre><code>##            Status
## Exposure    Diseased Not Diseased RowSum
##   Exposed          5           10     15
##   Unexposed       65           20     85
##   ColSum          70           30    100</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="introduction-to-bayesian-statistics.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can extract the values from the martix by typing</span></span>
<span id="cb58-2"><a href="introduction-to-bayesian-statistics.html#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="introduction-to-bayesian-statistics.html#cb58-3" aria-hidden="true" tabindex="-1"></a>data[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="introduction-to-bayesian-statistics.html#cb60-1" aria-hidden="true" tabindex="-1"></a>data[<span class="dv">9</span>]</span></code></pre></div>
<pre><code>## [1] 100</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="introduction-to-bayesian-statistics.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co">#etc</span></span></code></pre></div>
</div>
</div>
<div id="bayes-theorem" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Bayes’ Theorem</h2>
<p>The Bayes’ theorem (or law) determines the conditional probability of a hypothesis (i.e., event) being true given the evidence (i.e., data). This allows us to express our belief in a particular hypothesis (<span class="math inline">\(H\)</span>) or phenomenon, and how this believe should change after accounting for evidence (<span class="math inline">\(E\)</span>) or data.</p>
<p>The Bayes’ formula is:</p>
<p><span class="math display">\[Pr(H | E) = \frac{Pr(E|H)\cdot Pr(H)}{Pr(E)}\]</span>
Description of each component: H is the hypothesis; Pr(<span class="math inline">\(H\)</span>) is probability the hypothesis is true (before any evidence is present). This is the <strong>prior</strong>; Pr(<span class="math inline">\(E\)</span>) is probability of observing the given hypothesis in light of the evidence; Pr(<span class="math inline">\(E|H\)</span>) is the conditional probability of observing the data (i.e., evidence) given the hypothesis. Here, it indicates the compatibility between the data and hypothesis. This is our <strong>likelihood</strong>. Lastly, the Pr(<span class="math inline">\(H|E\)</span>) is conditional probability i.e., what we want to know – the probability of a hypothesis given after we observed the data. This is the <strong>posterior</strong> probability.</p>
<p>The expanded from of the formula is</p>
<p><span class="math display">\[Pr(H | E) = \frac{Pr(E|H)\cdot Pr(H)}{Pr(E|H) \cdot Pr(H) + Pr(E|H&#39;) \cdot Pr(H&#39;)}\]</span>
Where,</p>
<p><span class="math display">\[Pr(E) = Pr(E|H) \cdot Pr(H) + Pr(E|H&#39;) \cdot Pr(H&#39;)\]</span></p>
<div id="applying-bayes-rule-on-the-metallic-poisoning-data" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Applying Bayes’ Rule on the metallic poisoning data</h3>
<p>We believe that there 3 in 10 risk are poisoning with long-term exposure to elevated concentrations of arsenic from topsoil in Devon. In a previous survey in Cornwall, the prevalence was 35%, granted that these findings are based on a similar setting with residents having similar exposure status. How probable would the risks be in Devon?</p>
<p>Prepare the model set-up:</p>
<ul>
<li>Prior: We hypotheses that there is 3 in 10 risk: <span class="math display">\[Pr(H) = 3/10 = 0.3\]</span></li>
</ul>
<p></br></p>
<ul>
<li>Likelihood: The prevalence is 35.0% after observing the data if hypothesis is true: <span class="math display">\[Pr(E | H) = 0.35\]</span></li>
</ul>
<p></br></p>
<ul>
<li>Complements: <span class="math display">\[Pr(H’) = 1 – 0.3 = 0.7; Pr(E | H’) = 1 – 0.35 = 0.65\]</span></li>
</ul>
<p></br></p>
<ul>
<li>Posterior: <span class="math display">\[Pr(H | E) = \frac{Pr(E|H)\cdot Pr(H)}{Pr(E|H) \cdot Pr(H) + Pr(E|H&#39;) \cdot Pr(H&#39;)} = \frac{0.35\cdot 0.3}{0.35 \cdot 0.3 + 0.7 \cdot 0.65} = 0.1875 = 18.75%\]</span></li>
</ul>
<p></br></p>
<p>We can keep updating this belief by simply re-inserting the value for the new prevalence in Pr(<span class="math inline">\(H\)</span>) and computing its complement i.e., Pr(<span class="math inline">\(H&#39;\)</span>).</p>
<p><strong>TASK</strong>: Let’s try to compute the <strong>conditional</strong> probability using the Bayes Rule with the example below. We suspect that the risk for contracting some disease is 3 in 15 although the prevalence for the disease could be as low as 20% with exposure to its associated risk factors. What is Pr(<span class="math inline">\(H|E\)</span>)?</p>
</div>
</div>
<div id="bayesian-inference-with-probability-functions" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Bayesian Inference with Probability Functions</h2>
<p>Bayes’ Rule forms the crux of Bayesian inference. In this domain, we often rely on probability functions applied to the Bayes’ rule to conduct parameter estimation for our hypothesis with the given the data. This process is somewhat tricky because you will need to derive a model for predicting the posterior distribution. The formula from the Bayes’ Rule is the following: <span class="math display">\[Pr(H | E) = \frac{Pr(E|H)\cdot Pr(H)}{Pr(E)} &gt;&gt; posterior \propto likelihood \cdot prior\]</span></p>
<p>As explained in the lecture, we simply remove the denominators (i.e., which is a constant term in this context) which, in turn, renders the relationship in the above equation to be proportional.With minimal information, it is possible to estimate a parameter through probabilistic modelling using this relation. Here, is an example.</p>
<div id="bayesian-inference-with-binomial-beta-distribution" class="section level3" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Bayesian inference with Binomial-Beta distribution</h3>
<p>Suppose, in a small survey, a random sample of 50 people from a large population at risk of arsenic poisoning due to environmental exposure status were selected. Each person’s disease status was recorded as either <strong>“Diseased”</strong> or <strong>“None”</strong>. 19 of the respondents have found to be diseased and assign a Beta distribution with Beta(3,5). It is possible to predict the disease burden through Bayesian inference.</p>
<ul>
<li><p>Step 1: Let the proportion who are disease represent <span class="math inline">\(\theta\)</span></p></li>
<li><p>Step 2: Specify the model for the likelihood function. Here it is a Binomial function since we are dealing with proportions:
<span class="math display">\[\binom{50}{19}\theta^{19}(1-\theta)^{50-19}\]</span></p></li>
<li><p>Step 3: Specify the prior. Here, it’s the Beta distribution with <span class="math inline">\(\alpha\)</span> = 3 and <span class="math inline">\(\beta\)</span> = 5. Its form is <span class="math display">\[k\theta^{3-1}(1-\theta)^{5-1}\]</span></p></li>
<li><p>Step 4: Compute the posterior distribution by multiplying the binomial and beta functions together. All constant terms not having <span class="math inline">\(\theta\)</span> can be thrown away:</p></li>
</ul>
<p><span class="math display">\[(\theta^{19}(1-\theta)^{50-19}) \times (\theta^{3-1}(1-\theta)^{5-1})\]</span>
<span class="math display">\[\theta^{22-1}(1-\theta)^{36-1}\]</span>
As you can see the posterior distribution is a Beta distribution, with the parameters updated from the binomial model. When the posterior is in the same family as the prior, we say the prior is a <strong>conjugate</strong> for the model. Here, the Beta prior is a conjugate for the binomial model. We can use this to estimate our parameter with the following code:</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="introduction-to-bayesian-statistics.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set all possible values for theta </span></span>
<span id="cb63-2"><a href="introduction-to-bayesian-statistics.html#cb63-2" aria-hidden="true" tabindex="-1"></a>theta <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length =</span> <span class="dv">100</span>)</span>
<span id="cb63-3"><a href="introduction-to-bayesian-statistics.html#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the prior using the beta[3,5]</span></span>
<span id="cb63-4"><a href="introduction-to-bayesian-statistics.html#cb63-4" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">dbeta</span>(theta, <span class="dv">3</span>, <span class="dv">5</span>)</span>
<span id="cb63-5"><a href="introduction-to-bayesian-statistics.html#cb63-5" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the posterior sample from updated formula which becomes a conjugate </span></span>
<span id="cb63-6"><a href="introduction-to-bayesian-statistics.html#cb63-6" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> <span class="fu">dbeta</span>(theta, <span class="dv">22</span>, <span class="dv">36</span>)</span>
<span id="cb63-7"><a href="introduction-to-bayesian-statistics.html#cb63-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-8"><a href="introduction-to-bayesian-statistics.html#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(theta,posterior, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(posterior)<span class="sc">+</span><span class="dv">1</span>), <span class="at">main =</span> <span class="st">&quot;Posterior Probability (Prevalence)&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Posterior Density&quot;</span>, <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;Probability of Parameter: &quot;</span>, theta, <span class="st">&quot; [%]&quot;</span>)))</span></code></pre></div>
<p><img src="GEOG0125_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<p>The mid-point of the posterior curve with the highest density is the posterior estimate we are looking for in predicting the disease burden, which is roughly <code>0.4</code>. Let’s extract the estimate at <code>50%</code> of this sample using the <code>qbeta()</code> function. We can also extract the point on <code>2.5%</code> and <code>97.5%</code> to report the <code>95%</code> credible intervals, and let make sure that this estimate is reflected in the graphical output.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="introduction-to-bayesian-statistics.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># estimate mean 50% and 95% CrI with qbeta()</span></span>
<span id="cb64-2"><a href="introduction-to-bayesian-statistics.html#cb64-2" aria-hidden="true" tabindex="-1"></a>Mean <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fl">0.5</span>, <span class="dv">22</span>, <span class="dv">36</span>)</span>
<span id="cb64-3"><a href="introduction-to-bayesian-statistics.html#cb64-3" aria-hidden="true" tabindex="-1"></a>LB <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fl">0.025</span>, <span class="dv">22</span>, <span class="dv">36</span>)</span>
<span id="cb64-4"><a href="introduction-to-bayesian-statistics.html#cb64-4" aria-hidden="true" tabindex="-1"></a>UB <span class="ot">&lt;-</span> <span class="fu">qbeta</span>(<span class="fl">0.975</span>, <span class="dv">22</span>, <span class="dv">36</span>)</span>
<span id="cb64-5"><a href="introduction-to-bayesian-statistics.html#cb64-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-6"><a href="introduction-to-bayesian-statistics.html#cb64-6" aria-hidden="true" tabindex="-1"></a>Mean</span></code></pre></div>
<pre><code>## [1] 0.377914</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="introduction-to-bayesian-statistics.html#cb66-1" aria-hidden="true" tabindex="-1"></a>LB</span></code></pre></div>
<pre><code>## [1] 0.2599547</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="introduction-to-bayesian-statistics.html#cb68-1" aria-hidden="true" tabindex="-1"></a>UB</span></code></pre></div>
<pre><code>## [1] 0.506553</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="introduction-to-bayesian-statistics.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(theta,posterior, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(posterior)<span class="sc">+</span><span class="dv">1</span>), <span class="at">main =</span> <span class="st">&quot;Posterior Probability (Prevalence)&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Posterior Density&quot;</span>, <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">&quot;Probability of Parameter: &quot;</span>, theta, <span class="st">&quot; [%]&quot;</span>)), <span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span>
<span id="cb70-2"><a href="introduction-to-bayesian-statistics.html#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(<span class="at">x0=</span>Mean, <span class="at">y0=</span><span class="fu">max</span>(posterior)<span class="sc">+</span><span class="dv">1</span>, <span class="at">x1=</span>Mean, <span class="at">y1=</span><span class="dv">0</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb70-3"><a href="introduction-to-bayesian-statistics.html#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(<span class="at">x0=</span>LB, <span class="at">y0=</span><span class="fu">max</span>(posterior)<span class="sc">+</span><span class="dv">1</span>, <span class="at">x1=</span>LB, <span class="at">y1=</span><span class="dv">0</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb70-4"><a href="introduction-to-bayesian-statistics.html#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">segments</span>(<span class="at">x0=</span>UB, <span class="at">y0=</span><span class="fu">max</span>(posterior)<span class="sc">+</span><span class="dv">1</span>, <span class="at">x1=</span>UB, <span class="at">y1=</span><span class="dv">0</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb70-5"><a href="introduction-to-bayesian-statistics.html#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(theta,posterior, <span class="at">col=</span><span class="st">&quot;red&quot;</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="GEOG0125_files/figure-html/unnamed-chunk-46-1.png" width="672" /></p>
<div class="note">
<p><strong>INTERPRETATION</strong>: Combining this with the information from the binomial data, we get the posterior of Beta(<span class="math inline">\(\theta\)</span>, 22, 36). The above model’s estimated prevalence is <code>37.79%</code> with uncertainty of <code>25.9%</code> to <code>50.6%</code></p>
</div>
<p><br></p>
<p><strong>TASK</strong>: Try to derive the posterior model for a likelihood function with Poisson distribution and a prior with a gamma distribution. Multiple the two distribution and see if a conjugate is derived.</p>
<p>Poisson Distribution: <span class="math display">\[P(Y|\theta) = \frac{\theta^{y}}{y!} \cdot e^{-\theta}\]</span></p>
<p>Gamma Distribution: <span class="math display">\[P(\theta) = k\theta^{\alpha-1}\cdot e^{-\beta \cdot \theta}\]</span></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="generalized-linear-models.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="spatial-spatiotemporal-bayesian-models-using-inla.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/UCLPG-MSC-SGDS/GEOG0125/edit/main/04-WEEK_7.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["GEOG0125.pdf", "GEOG0125.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
